# Generated by Django 5.0.7 on 2025-01-02 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_number', models.PositiveIntegerField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchLeaderboard',
            fields=[
                ('leaderboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('rank', models.PositiveIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='afc_leaderboard_calc.match')),
            ],
        ),
        migrations.CreateModel(
            name='ResultImage',
            fields=[
                ('result_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='match_results/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_images', to='afc_leaderboard_calc.match')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OverallLeaderboard',
            fields=[
                ('leaderboard_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=255)),
                ('total_score', models.IntegerField()),
                ('rank', models.PositiveIntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_leaderboard', to='afc_leaderboard_calc.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='afc_leaderboard_calc.tournament'),
        ),
    ]
