# Generated by Django 5.0.7 on 2025-01-07 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afc_leaderboard_calc', '0001_initial'),
        ('afc_team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='overallleaderboard',
            old_name='player_name',
            new_name='team_name',
        ),
        migrations.RemoveField(
            model_name='matchleaderboard',
            name='player_name',
        ),
        migrations.AddField(
            model_name='match',
            name='mvp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchleaderboard',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='afc_team.team'),
        ),
        migrations.CreateModel(
            name='MatchTeamStats',
            fields=[
                ('teamstats_id', models.AutoField(primary_key=True, serialize=False)),
                ('kills', models.IntegerField()),
                ('match_leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afc_leaderboard_calc.matchleaderboard')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
