from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # path("admin/", admin.site.urls),
    # path('admin-login/', admin_login, name='admin_login'),
    path('create-event/', create_event, name='create_event'),
    path('edit-event/', edit_event, name='edit_event'),
    path('create-leaderboard/', create_leaderboard, name='create_leaderboard'),
    path('get-all-events/', get_all_events, name='get_all_events'),
    path('get-event-details/', get_event_details, name='get_event_details'),
    path('get-all-events-paginated/', get_all_events_paginated, name='get_all_events_paginated'),
    path('get-all-tournaments-and-scrims/', get_all_tournaments_and_scrims, name='get_all_tournaments_and_scrims'),
    path('get-all-tournaments-and-scrims-paginated/', get_all_tournaments_and_scrims_paginated, name='get_all_tournaments_and_scrims_paginated'),
    path('get-all-tournaments-and-scrims-separated/', get_all_tournaments_and_scrims_separated, name='get_all_tournaments_and_scrims_separated'),
    path('get-all-tournaments-and-scrims-separated-paginated/', get_all_tournaments_and_scrims_separated_paginated, name='get_all_tournaments_and_scrims_separated_paginated'),
    path('get-total-events-count/', get_total_events_count, name='get_total_events_count'),
    path('get-total-tournaments-count/', get_total_tournaments_count, name='get_total_tournaments_count'),
    path('get-total-scrims-count/', get_total_scrims_count, name='get_total_scrims_count'),
    path('get-upcoming-events-count/', get_upcoming_events_count, name='get_upcoming_events_count'),
    path('get-ongoing-events-count/', get_ongoing_events_count, name='get_ongoing_events_count'),
    path('get-completed-events-count/', get_completed_events_count, name='get_completed_events_count'),
    path('get-average-participants-per-event/', get_average_participants_per_event, name='get_average_participants_per_event'),
    path('get-most-popular-event-format/', get_most_popular_event_format, name='get_most_popular_event_format'),
    path('register-for-event/', register_for_event, name='register_for_event'),
    path('get-event-details-for-admin/', get_event_details_for_admin, name='get_event_details_for_admin'),
    path('seed-solo-players-to-stage/', seed_solo_players_to_stage, name='seed_solo_players_to_stage'),
    path('seed-stage-competitors-to-groups/', seed_stage_competitors_to_groups, name='seed_stage_competitors_to_groups'),
    path('disqualify-registered-competitor/', disqualify_registered_competitor, name='disqualify_registered_competitor'),
    path('reactivate-registered-competitor/', reactivate_registered_competitor, name='reactivate_registered_competitor'),
    path('delete-event/', delete_event, name='delete_event'),
    path('remove-all-stage-competitors-from-groups-with-their-discord-roles/', remove_all_stage_competitors_from_groups_and_their_discord_roles, name='remove_all_stage_competitors_from_groups'),
    path('send-match-room-details-notification-to-competitor/', send_match_room_details_notification_to_competitor, name='send_match_room_details_notification_to_competitor'),
    path('delete-stage/', delete_stage, name='delete_stage'),
    path('delete-group/', delete_group, name='delete_group'),
    path('discord-role-progress/', discord_role_progress, name='discord_role_progress'),
    path('retry-failed-discord-roles/', retry_failed_discord_roles, name='retry_failed_discord_roles'),
    path('get-stage-role-assignment-progress/', get_stage_role_assignment_progress, name='get_stage_role_assignment_progress'),
    path('get-all-role-progress/', get_all_role_progress, name='get_all_role_progress'),
    path('get-all-user-id-in-stage/', get_all_user_id_in_stage, name='get_all_user_id_in_stage'),
    path('get-all-user-id-in-group/', get_all_user_id_in_group, name='get_all_user_id_in_group'),
    path('delete-notifications-from-users-in-a-group/', delete_notifications_from_users_in_a_group, name='delete_notification_from_users_in_a_group'),
    path('check-if-user-registered-in-event/', check_if_user_registered_in_event, name='check_if_user_registered_in_event'),
    path('upload-solo-match-result/', upload_solo_match_result, name='upload_solo_match_result'),
    path('get-all-leaderboards/', get_all_leaderboards, name='get_all_leaderboards'),
    path('sync-group-discord-roles/', sync_group_discord_roles, name='sync_group_discord_roles'),
    path('reconcile-group-roles/', reconcile_group_roles, name='reconcile_group_roles'),
    path('get-all-leaderboard-details-for-event/', get_all_leaderboard_details_for_event, name='get_all_leaderboard_details_for_event'),
    path('advance-group-competitors-to-next-stage/', advance_group_competitors_to_next_stage, name='advance_group_competitors_to_next_stage'),
    path('edit-solo-match-result/', edit_solo_match_result, name='edit_solo_match_result'),
    path('edit-leaderboard/', edit_leaderboard, name='edit_leaderboard'),
    path('remove-non-nigeria-registered-competitors/', remove_non_nigeria_registered_competitors, name='remove_non_nigeria_registered_competitors'),
    path('delete-match/', delete_match, name='delete_match'),
    path('edit-match-details/', edit_match_details, name='edit_match_details'),
    path('create-leaderboard-manually/', create_leaderboard_manually, name='create_leaderboard_manually'),
    path('enter-solo-match-result-manual/', enter_solo_match_result_manual, name='enter_solo_match_result_manual'),
    path('enter-team-match-result-manual/', enter_team_match_result_manual, name='enter_team_match_result_manual'),
    path('edit-match-result/', edit_match_result, name='edit_match_result'),
    path('disqualify-player/', disqualify_player, name='disqualify_player'),
    path('disqualify-team/', disqualify_team, name='disqualify_team'),
    path('sync-event-registrations-with-discord-roles/', sync_event_registrations_with_discord_roles, name='sync_event_registrations_with_discord_roles'),
    path('get-event-details-not-logged-in/', get_event_details_not_logged_in, name='get_event_details_not_logged_in'),
    path('validate-team-roster-discord/', validate_team_roster_discord, name='validate_team_roster_discord'),
    path('get-drafted-events/', get_drafted_events, name='get_drafted_events'),
    path('get-my-drafted-events/', get_my_drafted_events, name='get_my_drafted_events'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)