# Generated by Django 5.0.7 on 2026-06-02 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('default_banner', models.ImageField(blank=True, null=True, upload_to='organization_banners/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('socials', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('sub_organizer', 'Sub-organizer')], default='sub_organizer', max_length=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], default='active', max_length=10)),
                ('can_create_events', models.BooleanField(default=False)),
                ('can_edit_events', models.BooleanField(default=False)),
                ('can_upload_results', models.BooleanField(default=False)),
                ('can_manage_registrations', models.BooleanField(default=False)),
                ('can_submit_designs', models.BooleanField(default=False)),
                ('can_view_metrics', models.BooleanField(default=False)),
                ('can_view_reviews', models.BooleanField(default=False)),
                ('can_manage_members', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='afc_organizers.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
