# Generated by Django 5.0.7 on 2026-06-02 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afc_organizers', '0002_seed_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardDesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('notes', models.TextField(blank=True, default='')),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='leaderboard_design_refs/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='open', max_length=12)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_design_requests', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_requests', to='afc_organizers.organization')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaderboard_design_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
