# Generated by Django 5.0.7 on 2026-05-07 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afc_tournament_and_scrims', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=80)),
                ('option_source', models.CharField(choices=[('TEAMS', 'Teams'), ('PLAYERS', 'Players'), ('NUMERIC', 'Numeric'), ('FREEFORM', 'Freeform')], max_length=16)),
                ('auto_gradable', models.BooleanField(default=False)),
                ('grader_key', models.CharField(blank=True, help_text='Key into stats_reader.GRADERS; null for `custom`.', max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('LOCKED', 'Locked'), ('PENDING_SETTLEMENT', 'Pending Settlement'), ('SETTLED', 'Settled'), ('VOIDED', 'Voided')], default='DRAFT', max_length=24)),
                ('opens_at', models.DateTimeField()),
                ('lock_at', models.DateTimeField()),
                ('min_stake_kobo', models.BigIntegerField(default=10000)),
                ('max_per_user_kobo', models.BigIntegerField(blank=True, null=True)),
                ('cancel_fee_bps', models.PositiveIntegerField(default=100)),
                ('rake_bps', models.PositiveIntegerField(default=500)),
                ('total_pool_kobo', models.BigIntegerField(default=0)),
                ('total_lines', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markets_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markets', to='afc_tournament_and_scrims.event')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markets', to='afc_tournament_and_scrims.match')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('ref_team_id', models.IntegerField(blank=True, null=True)),
                ('ref_player_id', models.IntegerField(blank=True, null=True)),
                ('ref_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('image', models.URLField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('cached_pool_kobo', models.BigIntegerField(default=0)),
                ('cached_wager_count', models.PositiveIntegerField(default=0)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='afc_wager.market')),
            ],
            options={
                'ordering': ['market', 'sort_order'],
            },
        ),
        migrations.AddField(
            model_name='market',
            name='suggested_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='afc_wager.marketoption'),
        ),
        migrations.AddField(
            model_name='market',
            name='winning_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='afc_wager.marketoption'),
        ),
        migrations.AddField(
            model_name='market',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markets', to='afc_wager.markettemplate'),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(choices=[('WINNER', 'Winner'), ('VOID_NO_WINNER', 'Void (No Winner)'), ('VOID_ADMIN', 'Void (Admin)'), ('VOID_SOLO_WAGER', 'Void (Solo Wager)')], max_length=24)),
                ('override_reason', models.TextField(blank=True, default='')),
                ('total_pool_kobo', models.BigIntegerField(default=0)),
                ('rake_kobo', models.BigIntegerField(default=0)),
                ('paid_out_kobo', models.BigIntegerField(default=0)),
                ('winners_count', models.PositiveIntegerField(default=0)),
                ('lines_count', models.PositiveIntegerField(default=0)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by_admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_confirmed', to=settings.AUTH_USER_MODEL)),
                ('final_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='afc_wager.marketoption')),
                ('market', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='settlement', to='afc_wager.market')),
                ('suggested_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='afc_wager.marketoption')),
            ],
        ),
        migrations.CreateModel(
            name='RakeTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kobo', models.BigIntegerField()),
                ('credit_txn_id', models.BigIntegerField(blank=True, help_text='afc_wallet.WalletTxn.id of the HOUSE_RAKE credit', null=True)),
                ('settlement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rake', to='afc_wager.settlement')),
            ],
        ),
        migrations.CreateModel(
            name='Wager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_stake_kobo', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SETTLED', 'Settled'), ('VOIDED', 'Voided'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=16)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('debit_txn_id', models.BigIntegerField(blank=True, help_text='afc_wallet.WalletTxn.id of the WAGER_PLACE debit', null=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wagers', to='afc_wager.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wagers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WagerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake_kobo', models.BigIntegerField()),
                ('payout_kobo', models.BigIntegerField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('VOID', 'Void')], max_length=8, null=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='afc_wager.marketoption')),
                ('wager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='afc_wager.wager')),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kobo', models.BigIntegerField()),
                ('credit_txn_id', models.BigIntegerField(blank=True, help_text='afc_wallet.WalletTxn.id of the WAGER_PAYOUT credit', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts_received', to=settings.AUTH_USER_MODEL)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='afc_wager.settlement')),
                ('wager_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='afc_wager.wagerline')),
            ],
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['status', 'lock_at'], name='afc_wager_m_status_b71e58_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['event', 'status'], name='afc_wager_m_event_i_56c8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['resolution', '-confirmed_at'], name='afc_wager_s_resolut_78dc15_idx'),
        ),
        migrations.AddIndex(
            model_name='wager',
            index=models.Index(fields=['user', '-placed_at'], name='afc_wager_w_user_id_b7f432_idx'),
        ),
        migrations.AddIndex(
            model_name='wager',
            index=models.Index(fields=['market', 'status'], name='afc_wager_w_market__cbd611_idx'),
        ),
        migrations.AddConstraint(
            model_name='wager',
            constraint=models.UniqueConstraint(fields=('user', 'market'), name='uniq_wager_per_user_market'),
        ),
        migrations.AddConstraint(
            model_name='wagerline',
            constraint=models.UniqueConstraint(fields=('wager', 'option'), name='uniq_line_per_wager_option'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['user', '-id'], name='afc_wager_p_user_id_ce7741_idx'),
        ),
    ]
