#!/bin/bash
# 04-sync-from-aws.sh - pull the live checkout, media, migrations, .env and ipinfo off the AWS box.
#
# Runs ON THE VPS as ubuntu. The VPS holds its own ed25519 key (~/.ssh/id_ed25519, generated by
# the operator) whose public half was appended to ubuntu@3.80.44.105:~/.ssh/authorized_keys, so
# this box can pull without any agent forwarding and can therefore run under nohup for the 2 GB
# media transfer.
#
# rsync is re-runnable: the first pass moves the bulk while AWS still serves players, the cutover
# pass (same command) moves only what changed since, in seconds (runbook section 10).
#
# '/*.log' (leading slash) excludes only the stray runserver logs at the repo ROOT. A bare '*.log'
# silently dropped the 103 uploaded Free Fire match logs in media/match_result_logs/ on the first
# pass (2026-09-11 14:50, caught by comparing file counts). Media is user data; never pattern-
# exclude inside it.
#
# What is copied: the WHOLE ~/AFC-B directory minus the venv (rebuilt fresh, 06-venv.sh) and
# bytecode. That deliberately carries three things git does not: the gitignored migration files
# (generated on the server, runbook trap 3), .env, and media/. Also /home/ubuntu/ipinfo, which
# afc/settings.py hardcodes as GEOIP_PATH.
#
# Proven by gates C1, C2, C4.

set -eu
SRC=ubuntu@3.80.44.105
LOG=/home/ubuntu/sync-$(date +%Y%m%d-%H%M%S).log

echo "sync start $(date -u +%FT%TZ)" | tee "$LOG"
# .env is excluded after the first pass on purpose: the cutover re-sync (2026-09-11 15:33)
# copied AWS's .env over the one 05-env-and-venv.sh had already pointed at the local database,
# and migrate --check failed with "Access denied for user 'admin'@'localhost'". The AWS values
# survive on disk as .env.aws-original from the first pass, which is the marker used here.
EXCL_ENV=""; test -f /home/ubuntu/AFC-B/.env.aws-original && EXCL_ENV="--exclude=/.env"
rsync -az --info=progress2,stats $EXCL_ENV \
  --exclude 'venv/' --exclude '__pycache__/' --exclude '*.pyc' \
  --exclude 'celerybeat-schedule*' --exclude '/*.log' \
  "$SRC:AFC-B/" /home/ubuntu/AFC-B/ 2>&1 | tee -a "$LOG"

rsync -az --info=stats "$SRC:ipinfo/" /home/ubuntu/ipinfo/ 2>&1 | tee -a "$LOG" || echo "(no ipinfo dir on source)" | tee -a "$LOG"

echo "sync done $(date -u +%FT%TZ)" | tee -a "$LOG"
echo "media files: $(find /home/ubuntu/AFC-B/media -type f | wc -l)  size: $(du -sh /home/ubuntu/AFC-B/media | cut -f1)" | tee -a "$LOG"
test -f /home/ubuntu/AFC-B/.env && echo "ENV_OK" | tee -a "$LOG"
