"""
Django settings for afc project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

from dotenv import load_dotenv
import os

# gettext_lazy, NOT gettext: settings are imported before Django's translation machinery is
# ready, so any string translated here has to stay unresolved until it is actually rendered.
# Used for the OAUTH2_PROVIDER["SCOPES"] descriptions, the one set of player-facing English
# sentences that lives in this file. See locale/<lang>/LC_MESSAGES/django.po.
from django.utils.translation import gettext_lazy as _

load_dotenv(os.path.join(BASE_DIR, ".env"))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# Env-driven so production can disable it (a DEBUG=True page leaks tracebacks/settings/SQL).
# Defaults to True for local dev; PRODUCTION MUST set the env var DEBUG=False.
DEBUG = os.getenv("DEBUG", "True").strip().lower() == "true"

# Env-driven, comma-separated (mirrors the DEBUG pattern above). Defaults to "*" so local dev and
# the EB/ALB health checks that hit the instance by IP keep working. PRODUCTION SHOULD set the
# real hostnames, e.g. ALLOWED_HOSTS=api.africanfreefirecommunity.com,africanfreefirecommunity.com
# (The old afc.pythonanywhere.com / 98.94.15.73 entries were stale - AFC now runs on AWS EC2.)
ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "*").split(",") if h.strip()]


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
MINTROUTE_SECRET_KEY = os.getenv("MINTROUTE_SECRET_KEY")
MINTROUTE_ACCESS_KEY = os.getenv("MINTROUTE_ACCESS_KEY")
MINTROUTE_USERNAME = os.getenv("MINTROUTE_USERNAME")
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_celery_beat',
    'afc_auth',
    'afc_team',
    'afc_tournament_and_scrims',
    'afc_shop',
    'afc_awards',
    'afc_leaderboard',
    'afc_player',
    'afc_player_market',
    'afc_ocr',
    'afc_rankings',
    'afc_organizers',
    'afc_partner_api',
    'afc_sponsors',
    'oauth2_provider',
    'afc_sso',
    # AFC's own WhatsApp Cloud API integration (message log, template registry,
    # webhook). Replaces the Kapso and Zernio middlemen; see afc_whatsapp/apps.py.
    'afc_whatsapp',
    # Always-on, REUSABLE site feedback (owner backlog item 29). A form is DATA (FeedbackForm +
    # ordered FeedbackFields), so a second purpose is a row rather than a migration. See
    # afc_feedback/models.py.
    'afc_feedback',
    # Organisations apply to become AFC partners themselves, instead of emailing their
    # details for an admin to retype (owner 2026-08-04). Approval provisions through
    # afc_sso/provisioning.py and afc_partner_api, so there is no second way to create a
    # partner. See afc_partner_apply/models.py.
    'afc_partner_apply',
]

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
# Which Gemini model the OCR teacher calls. Flash is ~2x faster than Pro (≈12s vs ≈26s on a FF
# result screen) and reads the standings just as well, so it is the default. The synchronous prod
# request was timing out on Pro. Env-overridable (set GEMINI_MODEL=gemini-2.5-pro to trade speed for
# a touch more accuracy). Read at call time by afc_ocr.services.gemini.call_gemini.
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

# Socket timeout (seconds) for the synchronous Gemini OCR call. Read at call time by
# afc_ocr.services.gemini.call_gemini via getattr(settings, "GEMINI_HTTP_TIMEOUT", 20). Kept
# comfortably UNDER the prod ~30s gateway (ALB / Elastic Beanstalk) budget so a slow or hung
# Gemini read fails cleanly on our side (turned into a friendly 503 by upload_ocr_session)
# instead of the gateway returning a raw 502/504 to the user. Env-overridable so a Pro model or
# a slow network can be given more headroom without a redeploy.
GEMINI_HTTP_TIMEOUT = int(os.getenv("GEMINI_HTTP_TIMEOUT", "20"))

# Translations (news/events/notifications/emails via afc_auth.translation) run on DeepL, NOT Gemini
# (owner 2026-06-20) - DeepL is purpose-built for translation with a generous free tier. Gemini above
# stays ONLY for OCR. A DeepL FREE key ends in ":fx" (the engine auto-routes it to api-free.deepl.com;
# a Pro key uses api.deepl.com). Set in the environment (DEEPL_API_KEY), never hardcoded.
DEEPL_API_KEY = os.getenv("DEEPL_API_KEY")

# Google Sign-In (owner 2026-06-20) - the OAuth 2.0 "Web application" Client ID used to VERIFY the
# Google ID token that the frontend's "Continue with Google" button produces (afc_auth.views.
# google_auth). It is the SAME id the frontend ships as NEXT_PUBLIC_GOOGLE_CLIENT_ID. Public value,
# but kept in the environment so local/prod can differ. When unset, google_auth returns a clean
# "not configured" 400 and the rest of auth is unaffected.
GOOGLE_OAUTH_CLIENT_ID = os.getenv("GOOGLE_OAUTH_CLIENT_ID")
# Client SECRET (owner 2026-06-21): needed only for the CUSTOM "Continue with Google" button,
# which uses the GIS code flow (popup -> auth code -> backend exchanges it for an id token, so
# the button can be a full-width AFC-styled button instead of Google's locked iframe). The
# original id-token (credential) path does NOT use this. Secret, env-only, never committed.
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv("GOOGLE_OAUTH_CLIENT_SECRET")

# ── AFC as an OpenID Connect provider ("Sign in with AFC") ────────────────────
# Partner orgs authenticate AFC players on their own sites. Which FIELDS each org
# receives is NOT configured here: it lives on AFCSSOApplication toggles and is
# enforced by AFCOAuth2Validator. See WEBSITE/tasks/afc-sso-provider-design.md.
#
# OIDC_RSA_PRIVATE_KEY signs ID tokens (RS256). It MUST come from the environment.
# An empty value disables signing, so a missing env var fails loudly at boot rather
# than quietly issuing unsigned tokens.
OIDC_RSA_PRIVATE_KEY = os.environ.get("AFC_OIDC_RSA_PRIVATE_KEY", "")

OAUTH2_PROVIDER = {
    "OIDC_ENABLED": True,
    "OIDC_RSA_PRIVATE_KEY": OIDC_RSA_PRIVATE_KEY,
    # Every claim a partner org receives, in the ID token and at /sso/userinfo/, is decided by
    # this validator, which delegates to afc_sso.claims.build_claims. Removing this line does
    # not disable SSO, it silently hands claim selection back to the library's default map and
    # bypasses AFC's four gates, so treat it as security-critical config.
    "OAUTH2_VALIDATOR_CLASS": "afc_sso.validators.AFCOAuth2Validator",
    # PKCE defaults to True in 3.4.0. Stated explicitly so nobody "simplifies" it away.
    "PKCE_REQUIRED": True,
    # AFC issues a PAIRWISE sub: every partner sees a DIFFERENT opaque id for the same
    # player (afc_sso/validators.py pairwise_sub), so two partners cannot join their
    # databases on AFC identity. The library defaults this to ["public"], which told
    # partners the exact opposite and would have been a reasonable thing for them to
    # rely on. Discovery must describe what we actually do.
    "OIDC_SUBJECT_TYPES_SUPPORTED": ["pairwise"],
    # ── RP-initiated logout (owner 2026-08-03) ────────────────────────────────────────
    # Turns /sso/logout/ on and makes `end_session_endpoint` appear in discovery, so a
    # partner can offer "sign out of AFC too" instead of leaving the player signed in at
    # AFC after signing out of the partner site.
    #
    # READ afc_sso/views.py AFCRPInitiatedLogoutView BEFORE CHANGING ANY OF THIS. The
    # library's own logout view deletes EVERY token the player holds, at every partner,
    # not just the partner asking (views/oidc.py do_logout filters on user + client_type
    # + grant_type and never on the application). That would let one partner cut a player
    # off from all the others. AFC mounts its own subclass ahead of the library's route
    # and scopes the deletion to the requesting application.
    "OIDC_RP_INITIATED_LOGOUT_ENABLED": True,
    # Ask the player before ending their AFC session. This is the spec's SHOULD, and it
    # is what stops a partner silently signing a player out of AFC in a hidden iframe.
    # AFC ships its own confirm page (afc_sso/templates/oauth2_provider/logout_confirm.html)
    # so it looks like the consent screen rather than a bare library form.
    "OIDC_RP_INITIATED_LOGOUT_ALWAYS_PROMPT": True,
    # Refuse an http post-logout redirect for a public client. Belt and braces: AFC's own
    # policy (afc_sso/redirect_policy.py) already refuses to REGISTER one outside
    # loopback, and every AFC partner is a confidential client.
    "OIDC_RP_INITIATED_LOGOUT_STRICT_REDIRECT_URIS": True,
    # An EXPIRED id_token_hint still identifies which player and which partner, and a
    # player signing out an hour later is the normal case rather than an attack. It
    # authorises nothing on its own: the hint only selects whose tokens are deleted, and
    # AFC scopes that to the partner that presented it.
    "OIDC_RP_INITIATED_LOGOUT_ACCEPT_EXPIRED_TOKENS": True,
    # i18n (owner 2026-08-03): these are the only English strings in this file a PLAYER ever
    # reads, so they are wrapped in gettext_lazy and translated in locale/<lang>/LC_MESSAGES/
    # django.po alongside the consent template itself. Lazy, not eager: settings load long
    # before the translation machinery is ready, so the string must not resolve until it is
    # rendered. afc_sso.claims.describe_scopes force-evaluates them with str() at call time,
    # under whatever language SSOLanguageMiddleware activated for that request.
    "SCOPES": {
        "openid": _("Confirm who you are on AFC"),
        "profile": _("Your in-game name, avatar, country and language"),
        "email": _("Your email address"),
        "afc.freefire": _("Your Free Fire UID"),
        "afc.team": _("Your current team and your role in it"),
        # These strings are the PROMISE shown to the player on the consent screen, so each one
        # has to match what afc_sso/claims.py actually releases. History carries event name and
        # slug only (no placement), and ranking carries points, rank and month (tier is a TEAM
        # attribute, team_tier, so it is not in a player claim). Change a resolver, change these.
        "afc.history": _("Tournaments you have played"),
        "afc.stats": _("Your match statistics"),
        "afc.ranking": _("Your AFC rank and ranking points"),
        "afc.standing": _("Whether your AFC account is in good standing"),
    },
    "DEFAULT_SCOPES": ["openid"],
}
# Swap django-oauth-toolkit's Application for ours. AFCSSOApplication (afc_sso/models.py)
# is the per-org permission record: the share_* toggles decide what a partner org may ever
# read about a player. Every call to oauth2_provider.models.get_application_model() in the
# library and in our code resolves to it because of this line.
#
# Ordering note, do not move this above the app: django.contrib.admin autodiscover imports
# oauth2_provider.admin, which resolves this setting EAGERLY at module import time
# (apps.get_model(...) with no lazy fallback), so pointing it at a model that does not exist
# crashes `manage.py` outright with LookupError. It is safe now that Task 2 has landed the model.
OAUTH2_PROVIDER_APPLICATION_MODEL = "afc_sso.AFCSSOApplication"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # i18n Phase 1 (owner 2026-06-15): pin request.locale (en/fr/pt) from the Accept-Language header.
    # Placed AFTER CommonMiddleware so it runs once the request line is in place; views/serializers
    # read it via afc_auth.locale_middleware.get_locale(request) and feed it to the translation
    # engine (afc_auth.translation.translate). Best-effort, never breaks a request. See locale_middleware.py.
    'afc_auth.locale_middleware.LocaleMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # "Sign in with AFC" auth bridge. AFC has no Django session, so the OIDC authorize view
    # would never see a logged-in player. This resolves the existing auth_token cookie into
    # request.user, and ONLY for /sso/ paths, so no other endpoint gains implicit cookie auth.
    # Sits directly after AuthenticationMiddleware so it overrides the session-derived user
    # on those paths. See afc_sso/middleware.py.
    'afc_sso.middleware.SSOSessionTokenMiddleware',
    # Activates the player's language for /sso/ requests ONLY, so the Django-rendered consent
    # screen and the scope descriptions come out in the language they chose. Sits directly
    # after the bridge above because it reads the request.user that bridge resolves, and its
    # preference order is User.language first (the same signal the transactional emails use)
    # then the Accept-Language locale LocaleMiddleware already parsed. See afc_sso/middleware.py.
    'afc_sso.middleware.SSOLanguageMiddleware',
    # Sitewide automatic admin audit log. Sits AFTER AuthenticationMiddleware so the request
    # pipeline + URL resolution are in place; it resolves the acting User from the Bearer
    # SessionToken itself (AFC does not use Django sessions) and records every admin/staff
    # mutation into afc_auth.AuditLog. Best-effort, never breaks a request. See afc_auth/middleware.py.
    'afc_auth.middleware.AuditLogMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ── CORS: allow the super-admin "act-as" (god-mode) request headers ────────────
# The frontend axios interceptor sets X-Act-As-Org / X-Act-As-Vendor when a super admin is
# operating inside an organizer/vendor dashboard (see afc_auth/act_as.py). These are CUSTOM
# request headers, so they must be added to the CORS allow-list or the browser preflight
# blocks them cross-origin. Everything else stays on django-cors-headers' defaults.
from corsheaders.defaults import default_headers as _cors_default_headers
CORS_ALLOW_HEADERS = (*_cors_default_headers, "x-act-as-org", "x-act-as-vendor")


ROOT_URLCONF = 'afc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# ── CORS / CSRF (hardened 2026-06-28) ─────────────────────────────────────────
# The browser frontend (africanfreefirecommunity.com) calls this API cross-origin, so CORS must
# permit the FE origin. The OLD config (CORS_ORIGIN_ALLOW_ALL=True together with
# CORS_ALLOW_CREDENTIALS=True) made django-cors-headers echo back ANY Origin with
# Access-Control-Allow-Credentials:true, i.e. every site on the internet could make credentialed
# cross-origin calls against this API. We now allow-all ONLY in local dev (DEBUG) and fall back to an
# explicit allowlist in production. The list is env-overridable (CORS_ALLOWED_ORIGINS=comma,separated)
# so the owner can add an origin without a code deploy.
#
# Note: the app authenticates with a Bearer SessionToken HEADER (not cookies), so "credentials" here
# only matters for the Django admin session + any cookie flow; the allowlist below is the FE origins.
# Consumed by corsheaders.middleware.CorsMiddleware (MIDDLEWARE above).
_DEFAULT_CORS_ORIGINS = ",".join([
    "https://africanfreefirecommunity.com",
    "https://www.africanfreefirecommunity.com",
    "http://localhost:3000",
    "http://127.0.0.1:5500",
])
CORS_ALLOWED_ORIGINS = [o.strip() for o in os.getenv("CORS_ALLOWED_ORIGINS", _DEFAULT_CORS_ORIGINS).split(",") if o.strip()]
CORS_ALLOW_CREDENTIALS = True
# Allow-all ONLY in dev; in prod (DEBUG=False) the explicit allowlist above is enforced. Mirrors the
# `RANKINGS_RECALC_SYNC = DEBUG` env pattern used elsewhere in this file. (CORS_ALLOW_ALL_ORIGINS is
# the modern name for the deprecated CORS_ORIGIN_ALLOW_ALL.)
CORS_ALLOW_ALL_ORIGINS = DEBUG

# CSRF trusted origins: required for the Django admin (session-cookie POSTs) over HTTPS and for any
# cross-origin POST. Mirror the CORS allowlist plus the API's own HTTPS origin. Env-overridable
# (CSRF_TRUSTED_ORIGINS=comma,separated). Read by django.middleware.csrf.CsrfViewMiddleware.
_DEFAULT_CSRF_ORIGINS = ",".join([
    "https://africanfreefirecommunity.com",
    "https://www.africanfreefirecommunity.com",
    "https://api.africanfreefirecommunity.com",
    "http://localhost:3000",
    "http://127.0.0.1:5500",
])
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv("CSRF_TRUSTED_ORIGINS", _DEFAULT_CSRF_ORIGINS).split(",") if o.strip()]


WSGI_APPLICATION = 'afc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'database-1',
#         'USER': 'admin',
#         'PASSWORD': 'YellowMonkey69.',
#         'HOST': 'database-1.c0t8i0cyoxuq.us-east-1.rds.amazonaws.com',  # Or your remote host
#         'PORT': '3306',       # Or your custom port if different
#     }
# }

# Env-driven DB config. The defaults are the LOCAL dev values, so local keeps working with
# no env set. PRODUCTION MUST set DB_USER/DB_PASSWORD/DB_HOST (and DB_NAME) to a DEDICATED
# app user on the real DB host, NOT root@localhost. Deploying these root@localhost defaults
# to production is what causes the intermittent 1698 "Access denied for user 'root'@'localhost'"
# 500s (root@localhost uses socket auth, so a password/TCP login is rejected).
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST", "localhost"),
        'PORT': os.getenv("DB_PORT", "3306"),
        # Force the CONNECTION charset to utf8mb4 so 4-byte characters (emoji + some stylized
        # unicode in Free Fire player names, e.g. the OCR training labels) can be written.
        # Without this the connection defaulted to utf8mb3 and a 4-byte char raised
        # OperationalError 1366 "Incorrect string value" even though the columns are utf8mb4.
        'OPTIONS': {'charset': 'utf8mb4'},
        # Let a test run pick its own scratch database. Django otherwise derives one fixed
        # name ("test_" + NAME), so two `manage.py test` runs against the same MySQL server
        # fight over the same database: the second run finds it already there, and either
        # prompts or destroys the first run's schema mid-test. Set AFC_TEST_DB_NAME when
        # running suites in parallel (several agents, or tests alongside a watcher).
        # Unset, this is exactly Django's own default, so nothing changes for a normal run.
        'TEST': {'NAME': os.getenv("AFC_TEST_DB_NAME") or None},
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



AUTH_USER_MODEL = "afc_auth.User"

AUTHENTICATION_BACKENDS = [
    'afc_auth.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',  # Default authentication backend
]



# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# i18n Phase 0 (owner 2026-06-15): the locales AFC supports. English (default), French, Portuguese.
# These match afc_auth.models.User.LANGUAGE_CHOICES and the frontend i18n locales. Harmless on its
# own (no catalogs wired yet); Phase 1+ uses it for Django's translation machinery if needed.
LANGUAGES = [
    ("en", "English"),
    ("fr", "Français"),
    ("pt", "Português"),
]

# i18n (owner 2026-08-03): where Django's gettext catalogs live. ONE surface uses them, the
# "Sign in with AFC" consent screen (afc_sso/templates/afc_sso/authorize.html) plus the scope
# descriptions in OAUTH2_PROVIDER["SCOPES"] above and the refusal messages in afc_sso/views.py.
# Everything else the player reads is either a Next.js page (frontend/messages/*) or an email
# (afc_auth/email_i18n.py); this exists because a Django-rendered template can use neither.
#
# English is the source language and has NO catalog: an untranslated string renders as its own
# msgid. locale/fr and locale/pt are HAND-WRITTEN .po files (DeepL is not in the loop here),
# compiled to the committed .mo binaries with `manage.py compile_locales`.
LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Redis URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# Rankings recalc: run inline on commit in dev (no worker needed); set False + run
# `celery -A afc worker -Q rankings_recalc` in production for async recalculation.
# Independently env-overridable (2026-06-28) so prod can run DEBUG=False WITHOUT being forced into
# async, which would silently no-op recalculation unless that worker is running. Defaults to DEBUG
# (inline in dev, async in prod). If you flip DEBUG=False but have NOT started the worker, set
# RANKINGS_RECALC_SYNC=True in the prod .env to keep recalculation inline.
RANKINGS_RECALC_SYNC = os.getenv("RANKINGS_RECALC_SYNC", str(DEBUG)).strip().lower() == "true"

# OCR ML retrain loop (Phase 4): same inline-in-dev pattern as RANKINGS_RECALC_SYNC.
# When True (defaults to DEBUG) the afc_ocr tasks can be invoked inline without a Celery
# worker (handy for local testing / management runs). In production set it False and run a
# dedicated worker for the ocr_ml queue: `celery -A afc worker -Q ocr_ml` (+ `celery -A afc beat`
# for the nightly autolabel / weekly retrain-trigger schedule wired in afc/celery_config.py).
# Independently env-overridable (2026-06-28), same rationale as RANKINGS_RECALC_SYNC above: flipping
# DEBUG=False must not silently no-op the OCR ML tasks. Set OCR_ML_SYNC=True in prod .env to force
# inline if the ocr_ml worker is not running.
OCR_ML_SYNC = os.getenv("OCR_ML_SYNC", str(DEBUG)).strip().lower() == "true"

# WhatsApp sends (afc_whatsapp/tasks.py): same inline-in-dev pattern as the two above.
# When True (defaults to DEBUG) queue_template / queue_text run the send inline, so local dev
# needs no worker. In production leave it False and run a dedicated worker for the whatsapp
# queue: `celery -A afc worker -Q whatsapp`. Set WHATSAPP_SYNC=True in the prod .env only if
# that worker is not running, otherwise queued messages would sit in the broker unsent.
WHATSAPP_SYNC = os.getenv("WHATSAPP_SYNC", str(DEBUG)).strip().lower() == "true"

# OCR inference routing (Phase 3). The upload path tries the self-hosted local student first
# and only escalates to Gemini when the confidence gate is not satisfied (afc_ocr/services/
# ocr_confidence). All env-overridable so the cost/accuracy trade can be tuned in prod.
#   OCR_LOCAL_FIRST     - master switch for local-first routing (False => always Gemini).
#   OCR_GEMINI_FALLBACK - allow Gemini as the fallback/teacher (False => local best-effort
#                         only; combined with a missing GEMINI_API_KEY this is the zero-API
#                         budget mode the platform must survive in).
#   OCR_GATE_*          - the gate thresholds (see ocr_confidence.gate).
# The active local model bundle is resolved at runtime by afc_ocr.services.model_registry
# (media/models/current); no path is hardcoded here.
OCR_LOCAL_FIRST = os.getenv("OCR_LOCAL_FIRST", "True").strip().lower() == "true"
OCR_GEMINI_FALLBACK = os.getenv("OCR_GEMINI_FALLBACK", "True").strip().lower() == "true"
OCR_GATE_MIN_MEAN_SCORE = float(os.getenv("OCR_GATE_MIN_MEAN_SCORE", "0.80"))
OCR_GATE_MIN_NAMED_FRAC = float(os.getenv("OCR_GATE_MIN_NAMED_FRAC", "0.70"))
OCR_GATE_MAX_OVERSIZED_FRAC = float(os.getenv("OCR_GATE_MAX_OVERSIZED_FRAC", "0.15"))

# OCR upload image guards (A8). Read by afc_ocr.services.image_validate.validate_ocr_images,
# which the OCR upload views (afc_ocr.views.upload_ocr_session, afc_leaderboard.views.ocr_extract
# and afc_leaderboard.views.ocr_job_create) call before any Gemini read: a per-file byte cap plus a
# max file count keep a single synchronous upload bounded so it stays inside the request budget.
# NOTE (deliberate): we do NOT set a global DATA_UPLOAD_MAX_MEMORY_SIZE / FILE_UPLOAD_MAX_MEMORY_SIZE
# here - other endpoints (shop / design-asset uploads) rely on their own larger caps and a
# restrictive global would break them; these app-level checks are authoritative for the OCR paths
# only. 10 MB mirrors afc_player_market.MAX_POST_IMAGE_BYTES (a phone screenshot is well under that).
OCR_MAX_IMAGE_BYTES = int(os.getenv("OCR_MAX_IMAGE_BYTES", str(10 * 1024 * 1024)))  # 10 MB / file
OCR_MAX_IMAGES = int(os.getenv("OCR_MAX_IMAGES", "8"))                              # files / request


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}



DISCORD_REDIRECT_URI = "https://api.africanfreefirecommunity.com/auth/connect-discord/callback/"
DISCORD_GUILD_ID = "920726990607237160"
import os
DISCORD_BOT_TOKEN = os.getenv("DISCORD_BOT_TOKEN")
DISCORD_CLIENT_ID = os.getenv("DISCORD_CLIENT_ID")
DISCORD_CLIENT_SECRET = os.getenv("DISCORD_CLIENT_SECRET")
DISCORD_TOURNAMENT_DETTY_SOLOS_ROLE_ID = "1447745369403297955"

# Public base for THIS api, used to turn a stored media path into an absolute URL for a
# third party. The SSO claim builder has no Django request to call build_absolute_uri on
# (oauthlib passes its own request object), and a partner site cannot resolve "/media/..."
# against its own domain. Env-overridable so local dev can point at localhost.
AFC_API_BASE_URL = os.getenv("AFC_API_BASE_URL", "https://api.africanfreefirecommunity.com")

FRONTEND_URL = "https://africanfreefirecommunity.com"
FRONTEND_URL_LOCAL = "http://localhost:3000"

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ── Production security hardening (2026-06-28) ────────────────────────────────
# These switch ON only when DEBUG is False (production), so local dev over plain http is unaffected.
# The app runs behind nginx terminating TLS; SECURE_PROXY_SSL_HEADER (above) tells Django the original
# request arrived over HTTPS, which makes the secure-cookie + redirect logic correct behind the proxy.
# This block is what makes flipping DEBUG=False on prod yield a properly hardened deployment (it also
# clears Django's `manage.py check --deploy` W012/W016 warnings). The remaining opt-in items
# (SSL_REDIRECT, HSTS) are env-gated and default OFF on purpose, see the notes inline.
if not DEBUG:
    # Django admin SESSION cookie + CSRF cookie are sent only over HTTPS (the app's own auth is a
    # Bearer token header, so this is about the admin/cookie surface). Clears W012 + W016.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Stop browsers MIME-sniffing responses into a different content type (XSS hardening).
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Clickjacking: never allow an AFC page to be framed. (XFrameOptionsMiddleware is already in
    # MIDDLEWARE and defaults to DENY; set explicitly so intent is unambiguous.)
    X_FRAME_OPTIONS = "DENY"

    # Force plain-HTTP requests to redirect to HTTPS at the Django layer. Default OFF (opt-in via
    # env) on purpose: nginx already redirects http->https, and a health check that hits the
    # instance directly over HTTP *without* the X-Forwarded-Proto header would receive a 301 and
    # could be marked unhealthy. Enable SECURE_SSL_REDIRECT=True in the prod .env once you've
    # confirmed health checks go through HTTPS / carry the forwarded-proto header.
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "False").strip().lower() == "true"

    # HSTS tells browsers "always use HTTPS for this host for N seconds". It is SEMI-PERMANENT
    # (browsers cache the directive), so enabling it carelessly can lock users out of any
    # non-HTTPS subdomain. OFF by default (0); turn on via env once confident EVERY subdomain is
    # HTTPS. Recommended when stable: SECURE_HSTS_SECONDS=31536000 + INCLUDE_SUBDOMAINS=True.
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "0"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv("SECURE_HSTS_INCLUDE_SUBDOMAINS", "False").strip().lower() == "true"
    SECURE_HSTS_PRELOAD = os.getenv("SECURE_HSTS_PRELOAD", "False").strip().lower() == "true"

# GEOIP_PATH = "/home/ubuntu/geoip"
GEOIP_PATH = "/home/ubuntu/ipinfo"

PAYSTACK_SECRET_KEY = os.getenv("PAYSTACK_SECRET_KEY")
PAYSTACK_PUBLIC_KEY = os.getenv("PAYSTACK_PUBLIC_KEY")
# Where Paystack redirects the buyer after a shop payment. MUST match the real FE route
# app/(user)/orders/success/ -> /orders/success ((user) is a route group, not in the URL).
# It previously pointed at /shop/orders/success, which 404s (payment still completed via the
# webhook, but the buyer landed on a dead page). This is the same success page Stripe uses.
PAYSTACK_CALLBACK_URL = "https://africanfreefirecommunity.com/orders/success"

# Stripe (paid events). Env-driven; TEST keys locally, LIVE keys set on the prod server only,
# never in git. STRIPE_WEBHOOK_SECRET is added once the webhook endpoint is registered.
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")

# Shipping (provider-agnostic, afc_shop/services/shipping.py). Both unset => shipping is
# DISABLED and checkout is unchanged (the FE courier picker shows nothing, shipping_fee=0).
# Set SHIPPING_PROVIDER to the chosen courier API ("terminal" | "shipbubble" | "gigl") and
# SHIPPING_API_KEY to that provider's key (sandbox locally, live on prod only, never in git)
# once the provider is confirmed and its client is wired in get_provider().
SHIPPING_PROVIDER = os.getenv("SHIPPING_PROVIDER", "")
SHIPPING_API_KEY = os.getenv("SHIPPING_API_KEY")


# ── AFC's OWN WhatsApp Cloud API integration (afc_whatsapp) ────────────────────────────────
# The replacement for the two middlemen AFC used to rent (Kapso for marketplace vendor alerts,
# Zernio for match room details): AFC talks to Meta directly. Consumed by afc_whatsapp/client.py
# (sends), afc_whatsapp/webhooks.py (the inbound endpoint at /whatsapp/webhook/) and
# afc_whatsapp/tasks.py (the Celery send task). Every value is env-driven: the gitignored .env
# locally, real server env vars on prod. NOTHING here may ever be committed with a value.
#
#   WHATSAPP_PHONE_NUMBER_ID      -> the Meta phone-number ID we send FROM (the AFC business
#                                    number). Found in Meta app dashboard > WhatsApp > API setup.
#   WHATSAPP_ACCESS_TOKEN         -> the Bearer token for the Graph API. Use a SYSTEM USER token
#                                    (permanent), not the 24-hour temporary token the dashboard
#                                    shows first, or every send starts failing a day after setup.
#   WHATSAPP_APP_SECRET           -> the Meta APP secret. Used to verify the X-Hub-Signature-256
#                                    HMAC on every inbound webhook POST. Without it the webhook
#                                    rejects everything (deliberate: this URL can rewrite delivery
#                                    history and flip a user's notification consent).
#   WHATSAPP_BUSINESS_ACCOUNT_ID  -> the WABA the number belongs to. Not needed to send; it is what
#                                    `manage.py sync_whatsapp_templates` reads the approved
#                                    template list from.
#   WHATSAPP_API_VERSION          -> Graph API version, default v21.0. Bump deliberately.
#   WHATSAPP_WEBHOOK_VERIFY_TOKEN -> a random string the OWNER invents and types into BOTH the Meta
#                                    webhook config and this env var. Meta echoes it back once, on
#                                    the GET handshake, to prove we own the URL.
WHATSAPP_PHONE_NUMBER_ID = os.getenv("WHATSAPP_PHONE_NUMBER_ID", "")
WHATSAPP_ACCESS_TOKEN = os.getenv("WHATSAPP_ACCESS_TOKEN", "")
WHATSAPP_APP_SECRET = os.getenv("WHATSAPP_APP_SECRET", "")
WHATSAPP_BUSINESS_ACCOUNT_ID = os.getenv("WHATSAPP_BUSINESS_ACCOUNT_ID", "")
WHATSAPP_API_VERSION = os.getenv("WHATSAPP_API_VERSION", "v21.0")
WHATSAPP_WEBHOOK_VERIFY_TOKEN = os.getenv("WHATSAPP_WEBHOOK_VERIFY_TOKEN", "")

# ── The two room templates ────────────────────────────────────────────────────────────────────
# WHATSAPP_ROOM_TEMPLATE       -> the room id and password message. Five variables, in order:
#                                 player name, event name, room id, room password, map.
# WHATSAPP_ROOM_3D_TEMPLATE    -> the 3D room joining steps, sent as a SECOND message and only
#                                 when the map is marked a 3D room (owner 2026-08-05). Two
#                                 variables: player name, event name.
#
# The 3D one DEFAULTS TO EMPTY on purpose, and empty means "do not send it". A template name that
# Meta has not approved fails at send time, and the failure would land on the message carrying the
# room password, which is the one message on AFC that a player cannot play without. So until the
# owner has an approved name to put here, 3D rooms simply send the room details alone, exactly as
# they did before. Set it once Meta approves `afc_room_3d_help`.
#
# BOTH LANGUAGES ARE EXPLICIT because `en` and `en_US` are DIFFERENT templates to Meta and sending
# with the wrong one fails. The 3D language falls back to the room-details language, since the two
# are approved together in practice.
WHATSAPP_ROOM_TEMPLATE = os.getenv("WHATSAPP_ROOM_TEMPLATE", "room_details")
WHATSAPP_ROOM_TEMPLATE_LANG = os.getenv("WHATSAPP_ROOM_TEMPLATE_LANG", "en_US")
WHATSAPP_ROOM_3D_TEMPLATE = os.getenv("WHATSAPP_ROOM_3D_TEMPLATE", "")
WHATSAPP_ROOM_3D_TEMPLATE_LANG = os.getenv(
    "WHATSAPP_ROOM_3D_TEMPLATE_LANG", WHATSAPP_ROOM_TEMPLATE_LANG)

# Shop checkout currency. Both shop payment paths (Paystack + Stripe, see
# afc_shop/stripe_checkout.py) charge in this currency, and Stripe Connect vendor
# payouts (afc_shop/connect.py) transfer in it too. Defaults to NGN to match the
# Paystack flow; env-overridable if the shop currency ever changes.
SHOP_CURRENCY = os.getenv("SHOP_CURRENCY", "NGN")

# Marketplace platform fee (Stripe Connect vendor payouts, Phase B3). The percentage
# AFC keeps off each marketplace order total before transferring the rest to the
# vendor via Stripe Connect (afc_shop/connect.py settle_order_payout). Default 0 (no
# cut) per the owner decision; set e.g. "2.5" to take 2.5%. Stored on each VendorPayout
# row at settle time so a later change never rewrites past payouts.
MARKETPLACE_FEE_PERCENT = os.getenv("MARKETPLACE_FEE_PERCENT", "0")
