"""
Django settings for afc project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

from dotenv import load_dotenv
import os

load_dotenv(os.path.join(BASE_DIR, ".env"))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# Env-driven so production can disable it (a DEBUG=True page leaks tracebacks/settings/SQL).
# Defaults to True for local dev; PRODUCTION MUST set the env var DEBUG=False.
DEBUG = os.getenv("DEBUG", "True").strip().lower() == "true"

# Env-driven, comma-separated (mirrors the DEBUG pattern above). Defaults to "*" so local dev and
# the EB/ALB health checks that hit the instance by IP keep working. PRODUCTION SHOULD set the
# real hostnames, e.g. ALLOWED_HOSTS=api.africanfreefirecommunity.com,africanfreefirecommunity.com
# (The old afc.pythonanywhere.com / 98.94.15.73 entries were stale - AFC now runs on AWS EC2.)
ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "*").split(",") if h.strip()]


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
MINTROUTE_SECRET_KEY = os.getenv("MINTROUTE_SECRET_KEY")
MINTROUTE_ACCESS_KEY = os.getenv("MINTROUTE_ACCESS_KEY")
MINTROUTE_USERNAME = os.getenv("MINTROUTE_USERNAME")
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'django_celery_beat',
    'afc_auth',
    'afc_leaderboard_calc',
    'afc_team',
    'afc_tournament_and_scrims',
    'afc_shop',
    'afc_awards',
    'afc_leaderboard',
    'afc_player',
    'afc_player_market',
    'afc_ocr',
    'afc_rankings',
    'afc_organizers',
    'afc_partner_api',
    'afc_sponsors',
]

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
# Which Gemini model the OCR teacher calls. Flash is ~2x faster than Pro (≈12s vs ≈26s on a FF
# result screen) and reads the standings just as well, so it is the default — the synchronous prod
# request was timing out on Pro. Env-overridable (set GEMINI_MODEL=gemini-2.5-pro to trade speed for
# a touch more accuracy). Read at call time by afc_ocr.services.gemini.call_gemini.
GEMINI_MODEL = os.getenv("GEMINI_MODEL", "gemini-2.5-flash")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Sitewide automatic admin audit log. Sits AFTER AuthenticationMiddleware so the request
    # pipeline + URL resolution are in place; it resolves the acting User from the Bearer
    # SessionToken itself (AFC does not use Django sessions) and records every admin/staff
    # mutation into afc_auth.AuditLog. Best-effort, never breaks a request. See afc_auth/middleware.py.
    'afc_auth.middleware.AuditLogMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ROOT_URLCONF = 'afc.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:5500",
    "http://localhost:3000",
]

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:5500",
    "http://localhost:3000",
]


WSGI_APPLICATION = 'afc.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'database-1',
#         'USER': 'admin',
#         'PASSWORD': 'YellowMonkey69.',
#         'HOST': 'database-1.c0t8i0cyoxuq.us-east-1.rds.amazonaws.com',  # Or your remote host
#         'PORT': '3306',       # Or your custom port if different
#     }
# }

# Env-driven DB config. The defaults are the LOCAL dev values, so local keeps working with
# no env set. PRODUCTION MUST set DB_USER/DB_PASSWORD/DB_HOST (and DB_NAME) to a DEDICATED
# app user on the real DB host — NOT root@localhost. Deploying these root@localhost defaults
# to production is what causes the intermittent 1698 "Access denied for user 'root'@'localhost'"
# 500s (root@localhost uses socket auth, so a password/TCP login is rejected).
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST", "localhost"),
        'PORT': os.getenv("DB_PORT", "3306"),
        # Force the CONNECTION charset to utf8mb4 so 4-byte characters (emoji + some stylized
        # unicode in Free Fire player names, e.g. the OCR training labels) can be written.
        # Without this the connection defaulted to utf8mb3 and a 4-byte char raised
        # OperationalError 1366 "Incorrect string value" even though the columns are utf8mb4.
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



AUTH_USER_MODEL = "afc_auth.User"

AUTHENTICATION_BACKENDS = [
    'afc_auth.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',  # Default authentication backend
]



# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Redis URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# Rankings recalc: run inline on commit in dev (no worker needed); set False + run
# `celery -A afc worker -Q rankings_recalc` in production for async recalculation.
RANKINGS_RECALC_SYNC = DEBUG

# OCR ML retrain loop (Phase 4): same inline-in-dev pattern as RANKINGS_RECALC_SYNC.
# When True (defaults to DEBUG) the afc_ocr tasks can be invoked inline without a Celery
# worker (handy for local testing / management runs). In production set it False and run a
# dedicated worker for the ocr_ml queue: `celery -A afc worker -Q ocr_ml` (+ `celery -A afc beat`
# for the nightly autolabel / weekly retrain-trigger schedule wired in afc/celery_config.py).
OCR_ML_SYNC = DEBUG

# OCR inference routing (Phase 3). The upload path tries the self-hosted local student first
# and only escalates to Gemini when the confidence gate is not satisfied (afc_ocr/services/
# ocr_confidence). All env-overridable so the cost/accuracy trade can be tuned in prod.
#   OCR_LOCAL_FIRST     - master switch for local-first routing (False => always Gemini).
#   OCR_GEMINI_FALLBACK - allow Gemini as the fallback/teacher (False => local best-effort
#                         only; combined with a missing GEMINI_API_KEY this is the zero-API
#                         budget mode the platform must survive in).
#   OCR_GATE_*          - the gate thresholds (see ocr_confidence.gate).
# The active local model bundle is resolved at runtime by afc_ocr.services.model_registry
# (media/models/current); no path is hardcoded here.
OCR_LOCAL_FIRST = os.getenv("OCR_LOCAL_FIRST", "True").strip().lower() == "true"
OCR_GEMINI_FALLBACK = os.getenv("OCR_GEMINI_FALLBACK", "True").strip().lower() == "true"
OCR_GATE_MIN_MEAN_SCORE = float(os.getenv("OCR_GATE_MIN_MEAN_SCORE", "0.80"))
OCR_GATE_MIN_NAMED_FRAC = float(os.getenv("OCR_GATE_MIN_NAMED_FRAC", "0.70"))
OCR_GATE_MAX_OVERSIZED_FRAC = float(os.getenv("OCR_GATE_MAX_OVERSIZED_FRAC", "0.15"))


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}



DISCORD_REDIRECT_URI = "https://api.africanfreefirecommunity.com/auth/connect-discord/callback/"
DISCORD_GUILD_ID = "920726990607237160"
import os
DISCORD_BOT_TOKEN = os.getenv("DISCORD_BOT_TOKEN")
DISCORD_CLIENT_ID = os.getenv("DISCORD_CLIENT_ID")
DISCORD_CLIENT_SECRET = os.getenv("DISCORD_CLIENT_SECRET")
DISCORD_TOURNAMENT_DETTY_SOLOS_ROLE_ID = "1447745369403297955"

FRONTEND_URL = "https://africanfreefirecommunity.com"
FRONTEND_URL_LOCAL = "http://localhost:3000"

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# GEOIP_PATH = "/home/ubuntu/geoip"
GEOIP_PATH = "/home/ubuntu/ipinfo"

PAYSTACK_SECRET_KEY = os.getenv("PAYSTACK_SECRET_KEY")
PAYSTACK_PUBLIC_KEY = os.getenv("PAYSTACK_PUBLIC_KEY")
# Where Paystack redirects the buyer after a shop payment. MUST match the real FE route
# app/(user)/orders/success/ -> /orders/success ((user) is a route group, not in the URL).
# It previously pointed at /shop/orders/success, which 404s (payment still completed via the
# webhook, but the buyer landed on a dead page). This is the same success page Stripe uses.
PAYSTACK_CALLBACK_URL = "https://africanfreefirecommunity.com/orders/success"

# Stripe (paid events). Env-driven; TEST keys locally, LIVE keys set on the prod server only,
# never in git. STRIPE_WEBHOOK_SECRET is added once the webhook endpoint is registered.
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")

# Kapso (WhatsApp Cloud API proxy). Consumed by afc_shop/services/kapso.py, which the marketplace
# fulfilment notify (afc_shop/fulfilment.py notify_vendor) calls to message product owners/vendors
# on a paid order. Env-driven; values live in the gitignored .env locally and as server env vars on
# prod, never in git.
#   KAPSO_API_KEY         -> auth for the Kapso proxy, sent as the "X-API-Key" request header.
#   KAPSO_PHONE_NUMBER_ID -> the Meta phone-number ID we send FROM (the AFC WhatsApp business number).
#   KAPSO_PROJECT_ID / KAPSO_WHATSAPP_CONFIG_ID -> not required for the send call, but kept for the
#   inbound webhook handler (built separately) and CLI tooling.
KAPSO_API_KEY = os.getenv("KAPSO_API_KEY")
KAPSO_PHONE_NUMBER_ID = os.getenv("KAPSO_PHONE_NUMBER_ID")
KAPSO_PROJECT_ID = os.getenv("KAPSO_PROJECT_ID")
KAPSO_WHATSAPP_CONFIG_ID = os.getenv("KAPSO_WHATSAPP_CONFIG_ID")
# WhatsApp message TEMPLATE used for the COLD first-contact "new order" notification.
# WhatsApp blocks free-form messages outside the recipient's 24h window, so a business-
# initiated order alert MUST be an approved template. notify_vendor (afc_shop/fulfilment.py)
# sends this template via send_whatsapp_template, then falls back to free-form buttons if
# it fails (e.g. not approved yet).
#   KAPSO_TEMPLATE_NAME -> the approved template's name (owner registered "vendor_new_order").
#   KAPSO_TEMPLATE_LANG -> the language code the template was APPROVED under. Meta treats
#     "en_US" and "en" as DIFFERENT and rejects a mismatch with error 132001, so this MUST
#     equal the template's actual language in WhatsApp Manager. Default "en_US"; override via env.
KAPSO_TEMPLATE_NAME = os.getenv("KAPSO_TEMPLATE_NAME", "vendor_new_order")
KAPSO_TEMPLATE_LANG = os.getenv("KAPSO_TEMPLATE_LANG", "en_US")
# OPTIONAL shared secret for verifying INBOUND webhook calls (afc_shop/whatsapp_webhook.py).
# When set, every POST to /shop/whatsapp/webhook/ must carry an "X-Webhook-Signature" header
# equal to the HMAC-SHA256 hex digest of the raw request body keyed with this secret; a
# mismatch is rejected with 403. When unset (the default, e.g. local dev), the webhook
# accepts unsigned POSTs exactly as before, so this is backward compatible. Set it on prod
# together with the matching secret on the Kapso/proxy side.
KAPSO_WEBHOOK_SECRET = os.getenv("KAPSO_WEBHOOK_SECRET")

# Shop checkout currency. Both shop payment paths (Paystack + Stripe, see
# afc_shop/stripe_checkout.py) charge in this currency, and Stripe Connect vendor
# payouts (afc_shop/connect.py) transfer in it too. Defaults to NGN to match the
# Paystack flow; env-overridable if the shop currency ever changes.
SHOP_CURRENCY = os.getenv("SHOP_CURRENCY", "NGN")

# Marketplace platform fee (Stripe Connect vendor payouts, Phase B3). The percentage
# AFC keeps off each marketplace order total before transferring the rest to the
# vendor via Stripe Connect (afc_shop/connect.py settle_order_payout). Default 0 (no
# cut) per the owner decision; set e.g. "2.5" to take 2.5%. Stored on each VendorPayout
# row at settle time so a later change never rewrites past payouts.
MARKETPLACE_FEE_PERCENT = os.getenv("MARKETPLACE_FEE_PERCENT", "0")
