# Generated by Django 5.0.7 on 2026-05-31 19:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afc_team', '0002_teamsocialmedialinks_follower_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GhostTeam',
            fields=[
                ('ghost_team_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('external_id', models.CharField(blank=True, max_length=200, null=True)),
                ('is_provisional', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('claim_status', models.CharField(choices=[('unclaimed', 'Unclaimed'), ('pending', 'Claim Pending'), ('claimed', 'Claimed'), ('revoked', 'Claim Revoked')], default='unclaimed', max_length=20)),
                ('claim_requested_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claim_revoked_at', models.DateTimeField(blank=True, null=True)),
                ('claim_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ghost_claims_approved', to=settings.AUTH_USER_MODEL)),
                ('claim_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ghost_claims_requested', to=settings.AUTH_USER_MODEL)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_ghost_teams', to='afc_team.team')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ghost_teams_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerMonthlyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('kill_pts', models.FloatField(default=0)),
                ('placement_pts', models.FloatField(default=0)),
                ('mvp_pts', models.FloatField(default=0)),
                ('finals_pts', models.FloatField(default=0)),
                ('team_win_pts', models.FloatField(default=0)),
                ('participation_pts', models.FloatField(default=0)),
                ('scrim_kill_pts', models.FloatField(default=0)),
                ('scrim_win_pts', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('total_kills', models.IntegerField(default=0)),
                ('mvp_count', models.IntegerField(default=0)),
                ('finals_appearances', models.IntegerField(default=0)),
                ('finalized', models.BooleanField(default=False)),
                ('is_zeroed', models.BooleanField(default=False)),
                ('zeroed_reason', models.CharField(blank=True, max_length=255)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quarter', models.PositiveSmallIntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('year', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('transfer_window_open', models.DateField()),
                ('transfer_window_close', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('tier_eval_run', models.BooleanField(default=False)),
                ('tier_eval_run_at', models.DateTimeField(blank=True, null=True)),
                ('scores_frozen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tier_eval_run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasons_evaluated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-quarter'],
            },
        ),
        migrations.CreateModel(
            name='RankingAuditLog',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_type', models.CharField(choices=[('tournament_result', 'Tournament Result'), ('scrim_result', 'Scrim Result'), ('prize_money', 'Prize Money'), ('social_media', 'Social Media Count'), ('roster', 'Roster Change'), ('ghost_claim', 'Ghost Claim'), ('tier_override', 'Tier Override'), ('ban_zeroing', 'Ban Zeroing'), ('transfer_window', 'Transfer Window')], max_length=30)),
                ('object_ref', models.CharField(blank=True, max_length=100)),
                ('action', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='afc_rankings.season')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerQuarterlyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.FloatField(default=0)),
                ('prize_money_pts', models.FloatField(default=0)),
                ('tier_assigned', models.IntegerField(blank=True, choices=[(0, 'Elite'), (1, 'Competitive'), (2, 'Rising'), (3, 'Entry')], null=True)),
                ('tier_source', models.CharField(blank=True, choices=[('team', 'From Team'), ('individual', 'Individual')], max_length=12, null=True)),
                ('tier_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('participated_in_tournaments', models.IntegerField(default=0)),
                ('meets_participation_floor', models.BooleanField(default=False)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('is_zeroed', models.BooleanField(default=False)),
                ('zeroed_reason', models.CharField(blank=True, max_length=255)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_scores', to=settings.AUTH_USER_MODEL)),
                ('team_at_evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_quarterly_evals', to='afc_team.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_quarterly_scores', to='afc_rankings.season')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMonthlyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('tournament_pts', models.FloatField(default=0)),
                ('scrim_pts', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('tournament_wins', models.IntegerField(default=0)),
                ('total_kills', models.IntegerField(default=0)),
                ('tournaments_played', models.IntegerField(default=0)),
                ('finalized', models.BooleanField(default=False)),
                ('is_zeroed', models.BooleanField(default=False)),
                ('zeroed_reason', models.CharField(blank=True, max_length=255)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('ghost_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_scores', to='afc_rankings.ghostteam')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_scores', to='afc_team.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamQuarterlyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_pts', models.FloatField(default=0)),
                ('scrim_pts', models.FloatField(default=0)),
                ('prize_money_pts', models.FloatField(default=0)),
                ('social_media_pts', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('tier_assigned', models.IntegerField(blank=True, choices=[(0, 'Elite'), (1, 'Competitive'), (2, 'Rising'), (3, 'Entry')], null=True)),
                ('tier_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('tier_overridden', models.BooleanField(default=False)),
                ('tier_override_reason', models.CharField(blank=True, max_length=255)),
                ('participated_in_tournaments', models.IntegerField(default=0)),
                ('meets_participation_floor', models.BooleanField(default=False)),
                ('insufficient_activity_note', models.CharField(blank=True, max_length=255)),
                ('tournament_wins', models.IntegerField(default=0)),
                ('total_kills', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('is_zeroed', models.BooleanField(default=False)),
                ('zeroed_reason', models.CharField(blank=True, max_length=255)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('ghost_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_scores', to='afc_rankings.ghostteam')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_quarterly_scores', to='afc_rankings.season')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_scores', to='afc_team.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamSeasonEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('roster_locked_at', models.DateTimeField(blank=True, null=True)),
                ('is_ghost', models.BooleanField(default=False)),
                ('late_entry', models.BooleanField(default=False)),
                ('ghost_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_enrollments', to='afc_rankings.ghostteam')),
                ('late_entry_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_enrollments_approved', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='afc_rankings.season')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_enrollments', to='afc_team.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamSeasonRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField(default=django.utils.timezone.now)),
                ('left_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roster_approvals', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_rosters', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='afc_rankings.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_rosters', to='afc_team.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamSocialSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_followers', models.PositiveIntegerField(default=0)),
                ('tiktok_followers', models.PositiveIntegerField(default=0)),
                ('combined_followers', models.PositiveIntegerField(default=0)),
                ('social_media_pts', models.FloatField(default=0)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_snapshots', to='afc_rankings.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_snapshots', to='afc_team.team')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_snapshots_verified', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferWindowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('opened', 'Opened'), ('closed', 'Closed'), ('extended', 'Extended')], max_length=10)),
                ('previous_open_date', models.DateField(blank=True, null=True)),
                ('previous_close_date', models.DateField(blank=True, null=True)),
                ('new_open_date', models.DateField(blank=True, null=True)),
                ('new_close_date', models.DateField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_window_changes', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_logs', to='afc_rankings.season')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnualLeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('entity_type', models.CharField(choices=[('team', 'Team'), ('player', 'Player')], max_length=6)),
                ('q1_score', models.FloatField(default=0)),
                ('q2_score', models.FloatField(default=0)),
                ('q3_score', models.FloatField(default=0)),
                ('q4_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_entries', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_entries', to='afc_team.team')),
            ],
            options={
                'indexes': [models.Index(fields=['year', 'entity_type', '-total_score'], name='afc_ranking_year_3dae5d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='annualleaderboardentry',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('year', 'team'), name='uniq_year_team_annual'),
        ),
        migrations.AddConstraint(
            model_name='annualleaderboardentry',
            constraint=models.UniqueConstraint(condition=models.Q(('player__isnull', False)), fields=('year', 'player'), name='uniq_year_player_annual'),
        ),
        migrations.AddConstraint(
            model_name='annualleaderboardentry',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('player__isnull', True), ('team__isnull', False)), models.Q(('player__isnull', False), ('team__isnull', True)), _connector='OR'), name='annual_team_xor_player'),
        ),
        migrations.AddIndex(
            model_name='ghostteam',
            index=models.Index(fields=['is_active'], name='afc_ranking_is_acti_877569_idx'),
        ),
        migrations.AddIndex(
            model_name='ghostteam',
            index=models.Index(fields=['claim_status'], name='afc_ranking_claim_s_11e89c_idx'),
        ),
        migrations.AddIndex(
            model_name='ghostteam',
            index=models.Index(fields=['claimed_by'], name='afc_ranking_claimed_000a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='playermonthlyscore',
            index=models.Index(fields=['month', '-total_score'], name='afc_ranking_month_50abc4_idx'),
        ),
        migrations.AddConstraint(
            model_name='playermonthlyscore',
            constraint=models.UniqueConstraint(fields=('player', 'month'), name='uniq_player_month_score'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['is_active'], name='afc_ranking_is_acti_e910b1_idx'),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['year', 'quarter'], name='afc_ranking_year_ee8517_idx'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.UniqueConstraint(fields=('year', 'quarter'), name='uniq_season_year_quarter'),
        ),
        migrations.AddIndex(
            model_name='rankingauditlog',
            index=models.Index(fields=['object_type', '-changed_at'], name='afc_ranking_object__ef540c_idx'),
        ),
        migrations.AddIndex(
            model_name='rankingauditlog',
            index=models.Index(fields=['changed_by', '-changed_at'], name='afc_ranking_changed_335cf2_idx'),
        ),
        migrations.AddIndex(
            model_name='playerquarterlyscore',
            index=models.Index(fields=['season', '-total_score'], name='afc_ranking_season__797905_idx'),
        ),
        migrations.AddIndex(
            model_name='playerquarterlyscore',
            index=models.Index(fields=['season', 'tier_assigned'], name='afc_ranking_season__b496c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='playerquarterlyscore',
            constraint=models.UniqueConstraint(fields=('player', 'season'), name='uniq_player_season_score'),
        ),
        migrations.AddIndex(
            model_name='teammonthlyscore',
            index=models.Index(fields=['month', '-total_score'], name='afc_ranking_month_842db8_idx'),
        ),
        migrations.AddIndex(
            model_name='teammonthlyscore',
            index=models.Index(fields=['team', 'month'], name='afc_ranking_team_id_18a7dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='teammonthlyscore',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('team', 'month'), name='uniq_team_month_score'),
        ),
        migrations.AddConstraint(
            model_name='teammonthlyscore',
            constraint=models.UniqueConstraint(condition=models.Q(('ghost_team__isnull', False)), fields=('ghost_team', 'month'), name='uniq_ghost_month_score'),
        ),
        migrations.AddConstraint(
            model_name='teammonthlyscore',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('ghost_team__isnull', True), ('team__isnull', False)), models.Q(('ghost_team__isnull', False), ('team__isnull', True)), _connector='OR'), name='team_month_team_xor_ghost'),
        ),
        migrations.AddIndex(
            model_name='teamquarterlyscore',
            index=models.Index(fields=['season', '-total_score'], name='afc_ranking_season__245e86_idx'),
        ),
        migrations.AddIndex(
            model_name='teamquarterlyscore',
            index=models.Index(fields=['season', 'tier_assigned'], name='afc_ranking_season__b5e7de_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamquarterlyscore',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('team', 'season'), name='uniq_team_season_score'),
        ),
        migrations.AddConstraint(
            model_name='teamquarterlyscore',
            constraint=models.UniqueConstraint(condition=models.Q(('ghost_team__isnull', False)), fields=('ghost_team', 'season'), name='uniq_ghost_season_score'),
        ),
        migrations.AddConstraint(
            model_name='teamquarterlyscore',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('ghost_team__isnull', True), ('team__isnull', False)), models.Q(('ghost_team__isnull', False), ('team__isnull', True)), _connector='OR'), name='team_qscore_team_xor_ghost'),
        ),
        migrations.AddIndex(
            model_name='teamseasonenrollment',
            index=models.Index(fields=['season', 'is_ghost'], name='afc_ranking_season__82dc7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamseasonenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('team', 'season'), name='uniq_team_season_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='teamseasonenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('ghost_team__isnull', False)), fields=('ghost_team', 'season'), name='uniq_ghost_season_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='teamseasonenrollment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('ghost_team__isnull', True), ('team__isnull', False)), models.Q(('ghost_team__isnull', False), ('team__isnull', True)), _connector='OR'), name='enrollment_team_xor_ghost'),
        ),
        migrations.AddIndex(
            model_name='teamseasonroster',
            index=models.Index(fields=['season', 'team'], name='afc_ranking_season__d9aa15_idx'),
        ),
        migrations.AddIndex(
            model_name='teamseasonroster',
            index=models.Index(fields=['season', 'player'], name='afc_ranking_season__8bf899_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamseasonroster',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('left_at__isnull', True)), fields=('season', 'player'), name='uniq_player_one_team_per_season'),
        ),
        migrations.AddConstraint(
            model_name='teamsocialsnapshot',
            constraint=models.UniqueConstraint(fields=('team', 'season'), name='uniq_team_season_social'),
        ),
        migrations.AddIndex(
            model_name='transferwindowlog',
            index=models.Index(fields=['season', '-changed_at'], name='afc_ranking_season__0063a6_idx'),
        ),
    ]
