# Generated by Django 5.0.7 on 2026-05-31 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afc_rankings', '0001_initial'),
        ('afc_team', '0002_teamsocialmedialinks_follower_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='annualleaderboardentry',
            name='uniq_year_team_annual',
        ),
        migrations.RemoveConstraint(
            model_name='annualleaderboardentry',
            name='uniq_year_player_annual',
        ),
        migrations.RemoveConstraint(
            model_name='teammonthlyscore',
            name='uniq_team_month_score',
        ),
        migrations.RemoveConstraint(
            model_name='teammonthlyscore',
            name='uniq_ghost_month_score',
        ),
        migrations.RemoveConstraint(
            model_name='teamquarterlyscore',
            name='uniq_team_season_score',
        ),
        migrations.RemoveConstraint(
            model_name='teamquarterlyscore',
            name='uniq_ghost_season_score',
        ),
        migrations.RemoveConstraint(
            model_name='teamseasonenrollment',
            name='uniq_team_season_enrollment',
        ),
        migrations.RemoveConstraint(
            model_name='teamseasonenrollment',
            name='uniq_ghost_season_enrollment',
        ),
        migrations.RemoveConstraint(
            model_name='teamseasonroster',
            name='uniq_player_one_team_per_season',
        ),
        migrations.AddConstraint(
            model_name='annualleaderboardentry',
            constraint=models.UniqueConstraint(fields=('year', 'team'), name='uniq_year_team_annual'),
        ),
        migrations.AddConstraint(
            model_name='annualleaderboardentry',
            constraint=models.UniqueConstraint(fields=('year', 'player'), name='uniq_year_player_annual'),
        ),
        migrations.AddConstraint(
            model_name='teammonthlyscore',
            constraint=models.UniqueConstraint(fields=('team', 'month'), name='uniq_team_month_score'),
        ),
        migrations.AddConstraint(
            model_name='teammonthlyscore',
            constraint=models.UniqueConstraint(fields=('ghost_team', 'month'), name='uniq_ghost_month_score'),
        ),
        migrations.AddConstraint(
            model_name='teamquarterlyscore',
            constraint=models.UniqueConstraint(fields=('team', 'season'), name='uniq_team_season_score'),
        ),
        migrations.AddConstraint(
            model_name='teamquarterlyscore',
            constraint=models.UniqueConstraint(fields=('ghost_team', 'season'), name='uniq_ghost_season_score'),
        ),
        migrations.AddConstraint(
            model_name='teamseasonenrollment',
            constraint=models.UniqueConstraint(fields=('team', 'season'), name='uniq_team_season_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='teamseasonenrollment',
            constraint=models.UniqueConstraint(fields=('ghost_team', 'season'), name='uniq_ghost_season_enrollment'),
        ),
    ]
