# Generated by Django 5.0.7 on 2026-06-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afc_rankings', '0003_rename_ghostteam_region_to_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingauditlog',
            name='object_type',
            field=models.CharField(choices=[('tournament_result', 'Tournament Result'), ('scrim_result', 'Scrim Result'), ('prize_money', 'Prize Money'), ('social_media', 'Social Media Count'), ('roster', 'Roster Change'), ('ghost_claim', 'Ghost Claim'), ('tier_override', 'Tier Override'), ('ban_zeroing', 'Ban Zeroing'), ('transfer_window', 'Transfer Window'), ('season', 'Season'), ('evaluation', 'Quarterly Evaluation'), ('scoring_config', 'Scoring Config'), ('event_tier', 'Tournament Tier Rule'), ('point_deduction', 'Point Deduction')], max_length=30),
        ),
    ]
