# Generated by Django 5.0.7 on 2026-06-01 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afc_rankings', '0004_alter_rankingauditlog_object_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_tier', models.PositiveSmallIntegerField(default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventTierRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=0)),
                ('match', models.CharField(choices=[('all', 'Match all'), ('any', 'Match any')], default='all', max_length=3)),
                ('conditions', models.JSONField(default=list)),
                ('tier', models.PositiveSmallIntegerField(choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3')], default=2)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='teamquarterlyscore',
            name='points_deducted',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='teamquarterlyscore',
            name='points_deducted_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='GhostPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ign', models.CharField(max_length=100)),
                ('slot', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ghost_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='afc_rankings.ghostteam')),
            ],
            options={
                'ordering': ['ghost_team', 'slot'],
                'indexes': [models.Index(fields=['ghost_team'], name='afc_ranking_ghost_t_d8d11f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoring_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['is_active'], name='afc_ranking_is_acti_e6015b_idx')],
            },
        ),
    ]
