# Generated by Django 5.0.7 on 2026-06-01 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afc_rankings', '0005_eventtierconfig_eventtierrule_and_more'),
        ('afc_team', '0002_teamsocialmedialinks_follower_count_and_more'),
        ('afc_tournament_and_scrims', '0002_event_prize_currency_event_prizepool_ngn_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCountingControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_winner', models.BooleanField(default=True)),
                ('count_placement', models.BooleanField(default=True)),
                ('count_kills', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counting_control', to='afc_tournament_and_scrims.event')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_counting_controls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('team', 'Team'), ('player', 'Player')], max_length=6)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_exclusions_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_exclusions', to='afc_tournament_and_scrims.event')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_exclusions', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_exclusions', to='afc_team.team')),
            ],
            options={
                'indexes': [models.Index(fields=['event'], name='afc_ranking_event_i_a7e674_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='resultexclusion',
            constraint=models.UniqueConstraint(fields=('event', 'team'), name='uniq_event_team_exclusion'),
        ),
        migrations.AddConstraint(
            model_name='resultexclusion',
            constraint=models.UniqueConstraint(fields=('event', 'player'), name='uniq_event_player_exclusion'),
        ),
        migrations.AddConstraint(
            model_name='resultexclusion',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('player__isnull', True), ('team__isnull', False)), models.Q(('player__isnull', False), ('team__isnull', True)), _connector='OR'), name='result_exclusion_team_xor_player'),
        ),
    ]
