# Generated by Django 5.0.7 on 2026-06-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afc_rankings', '0006_eventcountingcontrol_resultexclusion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsocialsnapshot',
            name='connected_by_team',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamsocialsnapshot',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teamsocialsnapshot',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamsocialsnapshot',
            name='tiktok_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
