# Generated by Django 5.0.7 on 2026-06-01 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afc_rankings', '0007_teamsocialsnapshot_connected_by_team_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='rankings_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='season',
            name='rankings_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='rankings_published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasons_rankings_published', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='season',
            name='tiers_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='season',
            name='tiers_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='tiers_published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seasons_tiers_published', to=settings.AUTH_USER_MODEL),
        ),
    ]
