# Generated by Django 5.0.7 on 2026-05-18 16:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=60, unique=True)),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='teams_logos/')),
                ('team_tag', models.CharField(max_length=5, null=True)),
                ('join_settings', models.CharField(choices=[('open', 'Open'), ('by_request', 'By Request')], max_length=20)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_banned', models.BooleanField(default=False)),
                ('team_tier', models.CharField(default='3', max_length=1)),
                ('team_description', models.CharField(default='We Love Playing Free Fire', max_length=200)),
                ('country', models.CharField(max_length=20)),
                ('total_earnings', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('team_captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_teams', to=settings.AUTH_USER_MODEL)),
                ('team_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_teams', to=settings.AUTH_USER_MODEL)),
                ('team_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('team_created', 'Team Created'), ('player_left', 'Player Left Team'), ('player_joined', 'Player Joined Team'), ('player_removed', 'Player Removed From Team'), ('role_assigned', 'Role Assigned to Player'), ('role_changed', 'Player Role Changed'), ('team_disbanded', 'Team Disbanded'), ('team_name_changed', 'Team Name Changed'), ('team_banned', 'Team Banned'), ('player_banned', 'Player Banned')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afc_team.team')),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_of_request', models.CharField(choices=[('unattended_to', 'Unattended To'), ('attended_to', 'Attended To')], default='unattended_to', max_length=20)),
                ('decision', models.CharField(blank=True, choices=[('approved', 'Approved'), ('denied', 'Denied')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, max_length=150, null=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_request', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_request', to='afc_team.team')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('invite_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status_of_invite', models.CharField(choices=[('unattended_to', 'Unattended To'), ('attended_to', 'Attended To')], default='unattended_to', max_length=20)),
                ('role_to_be_given_upon_acceptance', models.CharField(choices=[('team_captain', 'Team Captain'), ('vice_captain', 'Vice Captain'), ('member', 'Member'), ('coach', 'Coach'), ('manager', 'Manager'), ('analyst', 'Analyst')], default='member', max_length=20)),
                ('decision', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('declined', 'Declined')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afc_team.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_role', models.CharField(choices=[('team_captain', 'Team Captain'), ('vice_captain', 'Vice Captain'), ('member', 'Member'), ('coach', 'Coach'), ('manager', 'Manager'), ('analyst', 'Analyst')], default='member', max_length=20)),
                ('in_game_role', models.CharField(blank=True, choices=[('rusher', 'Rusher'), ('support', 'Support'), ('grenader', 'Grenader'), ('sniper', 'Sniper')], max_length=20, null=True)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='afc_team.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamSocialMediaLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afc_team.team')),
            ],
        ),
        migrations.AddConstraint(
            model_name='teammembers',
            constraint=models.UniqueConstraint(fields=('member',), name='unique_member_one_team'),
        ),
        migrations.AlterUniqueTogether(
            name='teammembers',
            unique_together={('team', 'member')},
        ),
    ]
