# Generated by Django 5.0.7 on 2026-05-18 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afc_team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('SHORTLISTED', 'Shortlisted'), ('INVITED', 'Invited to Trial'), ('TRIAL_ONGOING', 'Trial Ongoing'), ('ACCEPTED', 'Accepted'), ('TRIAL_EXTENDED', 'Trial Extended')], default='PENDING', max_length=20)),
                ('contact_unlocked', models.BooleanField(default=False)),
                ('invite_expires_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afc_team.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afc_team.team')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afc_player_market.recruitmentapplication')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitmentPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('TEAM_RECRUITMENT', 'Team Recruitment'), ('PLAYER_AVAILABLE', 'Player Available')], max_length=20)),
                ('post_expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('primary_role', models.CharField(blank=True, choices=[('IGL', 'In-Game Leader'), ('RUSHER', 'Rusher'), ('SUPPORT', 'Support'), ('SNIPER', 'Sniper'), ('GRENADE', 'Grenade')], max_length=50)),
                ('secondary_role', models.CharField(blank=True, choices=[('IGL', 'In-Game Leader'), ('RUSHER', 'Rusher'), ('SUPPORT', 'Support'), ('SNIPER', 'Sniper'), ('GRENADE', 'Grenade')], max_length=50)),
                ('availability_type', models.CharField(blank=True, choices=[('TRIAL', 'Trial'), ('PERMANENT', 'Permanent'), ('SCRIMS_ONLY', 'Scrims Only')], max_length=20)),
                ('additional_info', models.TextField(blank=True)),
                ('roles_needed', models.JSONField(blank=True, null=True)),
                ('minimum_tier_required', models.CharField(blank=True, choices=[('TIER_1', 'Tier 1'), ('TIER_2', 'Tier 2'), ('TIER_3', 'Tier 3')], max_length=50)),
                ('commitment_type', models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time')], max_length=20)),
                ('recruitment_criteria', models.TextField(blank=True)),
                ('countries', models.ManyToManyField(blank=True, related_name='team_recruitment_posts', to='afc_player_market.country')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='afc_player_market.country')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_posts', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='afc_team.team')),
            ],
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='recruitment_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afc_player_market.recruitmentpost'),
        ),
        migrations.CreateModel(
            name='DirectTrialInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_direct_invites', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_direct_invites', to='afc_team.team')),
                ('player_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_invites', to='afc_player_market.recruitmentpost')),
            ],
        ),
        migrations.CreateModel(
            name='TrialChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial_chat', to='afc_player_market.recruitmentapplication')),
            ],
        ),
        migrations.CreateModel(
            name='TrialChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='afc_player_market.trialchat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='TrialInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afc_player_market.recruitmentapplication')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afc_team.team')),
            ],
        ),
        migrations.CreateModel(
            name='TrialInviteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afc_player_market.recruitmentapplication')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afc_team.team')),
            ],
        ),
        migrations.AddIndex(
            model_name='recruitmentpost',
            index=models.Index(fields=['post_type'], name='afc_player__post_ty_dd1dde_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentpost',
            index=models.Index(fields=['country'], name='afc_player__country_f49d22_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentpost',
            index=models.Index(fields=['created_at'], name='afc_player__created_707bab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='directtrialinvite',
            unique_together={('team', 'player_post')},
        ),
    ]
