# Generated by Django 5.0.7 on 2026-06-07 12:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afc_player_market', '0001_initial'),
        ('afc_team', '0002_teamsocialmedialinks_follower_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('team', 'Team'), ('player', 'Player')], max_length=10)),
                ('category', models.CharField(choices=[('bad_tryout', 'Negative tryout experience'), ('scam', 'Scam / fraud'), ('abusive', 'Abusive conduct'), ('fake_post', 'Fake / misleading post'), ('other', 'Other')], default='other', max_length=20)),
                ('details', models.TextField()),
                ('evidence', models.ImageField(blank=True, null=True, upload_to='market_report_evidence/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewing', 'Reviewing'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('banned', 'Banned')], default='open', max_length=12)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='afc_player_market.recruitmentpost')),
                ('reported_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_reports_against', to=settings.AUTH_USER_MODEL)),
                ('reported_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_reports', to='afc_team.team')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_reports_filed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('player', 'Player'), ('team', 'Team')], max_length=10)),
                ('ban_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ban_duration', models.IntegerField(blank=True, null=True)),
                ('ban_end_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(default='No reason provided', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_bans_issued', to=settings.AUTH_USER_MODEL)),
                ('banned_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_bans', to=settings.AUTH_USER_MODEL)),
                ('banned_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_bans', to='afc_team.team')),
                ('source_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_bans', to='afc_player_market.marketreport')),
            ],
        ),
        migrations.AddIndex(
            model_name='marketreport',
            index=models.Index(fields=['status'], name='afc_player__status_68fe74_idx'),
        ),
        migrations.AddIndex(
            model_name='marketreport',
            index=models.Index(fields=['created_at'], name='afc_player__created_6d0453_idx'),
        ),
        migrations.AddIndex(
            model_name='marketban',
            index=models.Index(fields=['is_active'], name='afc_player__is_acti_8ee06b_idx'),
        ),
    ]
