# Generated by Django 5.0.7 on 2026-05-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afc_tournament_and_scrims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prize_currency',
            field=models.CharField(default='NGN', max_length=3),
        ),
        migrations.AddField(
            model_name='event',
            name='prizepool_ngn_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='usd_to_ngn_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='played_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stages',
            name='is_finals_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='finals_appearances',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='is_tournament_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='reached_finals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentteam',
            name='result_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
