# Generated by Django 5.0.7 on 2026-06-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afc_tournament_and_scrims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='discord_required',
            field=models.BooleanField(default=False),
        ),
    ]
