# Generated by Django 5.0.7 on 2026-06-02 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afc_organizers', '0001_initial'),
        ('afc_tournament_and_scrims', '0002_event_prize_currency_event_prizepool_ngn_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='afc_organizers.organization'),
        ),
    ]
