# Generated by Django 5.0.7 on 2026-06-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afc_tournament_and_scrims', '0003_event_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rankings_verified',
            field=models.BooleanField(default=False),
        ),
    ]
