# Generated by Django 5.0.7 on 2026-06-02 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afc_tournament_and_scrims', '0004_event_rankings_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='stages',
            name='champion_point_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stages',
            name='champion_point_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stages',
            name='point_rush_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stages',
            name='point_rush_reward',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='stages',
            name='point_rush_target_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_rush_sources', to='afc_tournament_and_scrims.stages'),
        ),
        migrations.AlterField(
            model_name='stages',
            name='stage_format',
            field=models.CharField(choices=[('br - normal', 'Battle Royale - Normal'), ('br - roundrobin', 'Battle Royale - Knockout'), ('cs - normal', 'Clash Squad - Normal'), ('cs - league', 'Clash Squad - League'), ('cs - knockout', 'Clash Squad - Knockout'), ('cs - double elimination', 'Clash Squad - Double Elimination'), ('cs - round robin', 'Clash Squad - Round Robin')], max_length=100),
        ),
    ]
