# Generated by Django 5.0.7 on 2026-06-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afc_tournament_and_scrims', '0005_stages_champion_point_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='partner_published',
            field=models.BooleanField(default=False),
        ),
    ]
