# Generated by Django 5.0.7 on 2026-06-03 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afc_tournament_and_scrims', '0006_event_partner_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagegroups',
            name='game_day',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stages',
            name='stage_format',
            field=models.CharField(choices=[('br - normal', 'Battle Royale - Normal'), ('br - roundrobin', 'Battle Royale - Knockout'), ('cs - normal', 'Clash Squad - Normal'), ('cs - league', 'Clash Squad - League'), ('cs - knockout', 'Clash Squad - Knockout'), ('cs - double elimination', 'Clash Squad - Double Elimination'), ('cs - round robin', 'Clash Squad - Round Robin'), ('br - round robin', 'Battle Royale - Round Robin')], max_length=100),
        ),
        migrations.CreateModel(
            name='RoundRobinGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_robin_groups', to='afc_tournament_and_scrims.stages')),
                ('teams', models.ManyToManyField(blank=True, related_name='round_robin_groups', to='afc_tournament_and_scrims.tournamentteam')),
            ],
        ),
        migrations.AddField(
            model_name='stagegroups',
            name='source_groups',
            field=models.ManyToManyField(blank=True, related_name='lobbies', to='afc_tournament_and_scrims.roundrobingroup'),
        ),
    ]
