# Generated by Django 5.0.7 on 2026-06-03 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afc_tournament_and_scrims', '0007_stagegroups_game_day_alter_stages_stage_format_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roundrobingroup',
            options={'ordering': ['order']},
        ),
    ]
