# Generated by Django 5.0.7 on 2026-06-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afc_tournament_and_scrims', '0008_alter_roundrobingroup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinvitetoken',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
