# Generated by Django 5.0.7 on 2026-05-07 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FxSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ngn_per_usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('source', models.CharField(default='manual', max_length=64)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('TIER_0', 'Tier 0'), ('TIER_LITE', 'Tier Lite')], default='TIER_0', max_length=16)),
                ('whatsapp_number', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('whatsapp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('discord_user_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('discord_linked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_tier', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('amount_kobo', models.BigIntegerField()),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_kobo', models.BigIntegerField(default=0)),
                ('locked_kobo', models.BigIntegerField(default=0, help_text='Amount held in active wagers; subset of balance_kobo.')),
                ('balance_purchased_kobo', models.BigIntegerField(default=0)),
                ('balance_won_kobo', models.BigIntegerField(default=0)),
                ('balance_gift_kobo', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kobo', models.BigIntegerField(help_text='Signed: positive=credit, negative=debit.')),
                ('kind', models.CharField(choices=[('DEPOSIT_PAYSTACK', 'Deposit Paystack'), ('DEPOSIT_STRIPE', 'Deposit Stripe'), ('DEPOSIT_CRYPTO', 'Deposit Crypto'), ('DEPOSIT_VOUCHER', 'Deposit Voucher'), ('WAGER_PLACE', 'Wager Place'), ('WAGER_REFUND', 'Wager Refund'), ('WAGER_PAYOUT', 'Wager Payout'), ('WAGER_CANCEL_FEE', 'Wager Cancel Fee'), ('HOUSE_RAKE', 'House Rake'), ('P2P_OUT', 'P2P Out'), ('P2P_IN', 'P2P In'), ('P2P_FEE', 'P2P Fee'), ('WITHDRAW_HOLD', 'Withdraw Hold'), ('WITHDRAW_REVERSAL', 'Withdraw Reversal'), ('REDEMPTION_DEBIT', 'Redemption Debit'), ('ADJUSTMENT', 'Adjustment')], max_length=32)),
                ('source_tag', models.CharField(choices=[('PURCHASED', 'Purchased'), ('WON', 'Won'), ('GIFT', 'Gift')], help_text='Origin bucket — drives spend ladder + gift-cap accounting.', max_length=16)),
                ('ref_type', models.CharField(blank=True, default='', max_length=64)),
                ('ref_id', models.CharField(blank=True, default='', max_length=128)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fx_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='afc_wallet.fxsnapshot')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='txns', to='afc_wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoucherRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_redemptions', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='afc_wallet.voucher')),
                ('txn', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='afc_wallet.wallettxn')),
            ],
        ),
        migrations.CreateModel(
            name='DepositIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rail', models.CharField(choices=[('PAYSTACK', 'Paystack'), ('STRIPE', 'Stripe'), ('CRYPTO', 'Crypto'), ('VOUCHER', 'Voucher')], max_length=16)),
                ('amount_kobo', models.BigIntegerField()),
                ('provider_ref', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_intents', to=settings.AUTH_USER_MODEL)),
                ('resulting_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='afc_wallet.wallettxn')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kobo', models.BigIntegerField()),
                ('rail', models.CharField(choices=[('PAYSTACK_TRANSFER', 'Paystack Transfer'), ('CRYPTO_USDT', 'Crypto USDT')], max_length=24)),
                ('destination', models.JSONField(help_text='Bank account or crypto wallet — keys vary by rail.')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=16)),
                ('cosign_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('AWAITING', 'Awaiting'), ('APPROVED', 'Approved')], default='NOT_REQUIRED', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals_approved', to=settings.AUTH_USER_MODEL)),
                ('hold_txn', models.ForeignKey(blank=True, help_text='The WITHDRAW_HOLD debit; reversed on reject.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='afc_wallet.wallettxn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_kind', models.CharField(choices=[('MARKET_CREATE', 'Market Create'), ('MARKET_LOCK', 'Market Lock'), ('MARKET_VOID', 'Market Void'), ('MARKET_SETTLE_AUTO', 'Market Settle (Auto)'), ('MARKET_SETTLE_OVERRIDE', 'Market Settle (Override)'), ('WALLET_FREEZE', 'Wallet Freeze'), ('WALLET_UNFREEZE', 'Wallet Unfreeze'), ('WALLET_ADJUSTMENT', 'Wallet Adjustment'), ('WITHDRAWAL_APPROVE', 'Withdrawal Approve'), ('WITHDRAWAL_REJECT', 'Withdrawal Reject'), ('WITHDRAWAL_COSIGN', 'Withdrawal Cosign'), ('VOUCHER_GENERATE', 'Voucher Generate'), ('VOUCHER_REVOKE', 'Voucher Revoke'), ('KYC_MANUAL_VERIFY', 'KYC Manual Verify'), ('KYC_REVOKE', 'KYC Revoke'), ('ROLE_ASSIGN', 'Role Assign'), ('ROLE_REVOKE', 'Role Revoke')], max_length=48)),
                ('target_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(max_length=128)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('ua', models.TextField(blank=True, default='')),
                ('signed_hmac', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', '-created_at'], name='afc_wallet__admin_u_a73b5a_idx'), models.Index(fields=['action_kind', '-created_at'], name='afc_wallet__action__dd2318_idx'), models.Index(fields=['target_type', 'target_id'], name='afc_wallet__target__8a33fb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['expires_at'], name='afc_wallet__expires_c56336_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettxn',
            index=models.Index(fields=['wallet', '-created_at'], name='afc_wallet__wallet__3db013_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettxn',
            index=models.Index(fields=['wallet', 'kind'], name='afc_wallet__wallet__61c3eb_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettxn',
            index=models.Index(fields=['wallet', 'source_tag'], name='afc_wallet__wallet__f1f522_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucherredemption',
            constraint=models.UniqueConstraint(fields=('voucher', 'user'), name='uniq_voucher_redemption_per_user'),
        ),
        migrations.AddIndex(
            model_name='depositintent',
            index=models.Index(fields=['user', '-created_at'], name='afc_wallet__user_id_c51699_idx'),
        ),
        migrations.AddIndex(
            model_name='depositintent',
            index=models.Index(fields=['provider_ref'], name='afc_wallet__provide_bc2740_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['status', '-created_at'], name='afc_wallet__status_d460e3_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['user', '-created_at'], name='afc_wallet__user_id_939b3d_idx'),
        ),
    ]
