# Generated by Django 5.0.7 on 2025-01-02 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afc_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='user_id',
        ),
    ]
