# Generated by Django 5.0.7 on 2026-05-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afc_auth', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
