# Generated by Django 5.0.7 on 2026-05-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afc_auth', '0003_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='role_name',
            field=models.CharField(choices=[('head_admin', 'Head Admin'), ('metrics_admin', 'Metrics Admin'), ('shop_admin', 'Shop Admin'), ('news_admin', 'News Admin'), ('event_admin', 'Event Admin'), ('teams_admin', 'Teams Admin'), ('partner_admin', 'Partner Admin'), ('sponsor_admin', 'Sponsor Admin')], max_length=20, unique=True),
        ),
    ]
