# Generated by Django 5.0.7 on 2026-06-03 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afc_organizers', '0004_eventcomment_organizationreport_eventrating'),
        ('afc_tournament_and_scrims', '0006_event_partner_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allow_all_native_afc', models.BooleanField(default=False)),
                ('can_read_events', models.BooleanField(default=False)),
                ('can_read_stages', models.BooleanField(default=False)),
                ('can_read_matches', models.BooleanField(default=False)),
                ('can_read_standings', models.BooleanField(default=False)),
                ('can_read_teams', models.BooleanField(default=False)),
                ('can_read_players', models.BooleanField(default=False)),
                ('include_placements', models.BooleanField(default=False)),
                ('include_kills', models.BooleanField(default=False)),
                ('include_damage', models.BooleanField(default=False)),
                ('include_assists', models.BooleanField(default=False)),
                ('include_rosters', models.BooleanField(default=False)),
                ('include_maps', models.BooleanField(default=False)),
                ('include_prize', models.BooleanField(default=False)),
                ('include_mvp', models.BooleanField(default=False)),
                ('allowed_events', models.ManyToManyField(blank=True, related_name='partner_grants', to='afc_tournament_and_scrims.event')),
                ('allowed_organizations', models.ManyToManyField(blank=True, related_name='partner_grants', to='afc_organizers.organization')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerApiKey',
            fields=[
                ('key_id', models.AutoField(primary_key=True, serialize=False)),
                ('key_prefix', models.CharField(db_index=True, max_length=16)),
                ('key_hash', models.CharField(max_length=64)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('rate_limit_per_min', models.PositiveIntegerField(default=60)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='afc_partner_api.partner')),
            ],
        ),
    ]
