"""
tools/export_event_contract.py - the event contract as JSON, for the frontend's form checker.

WHY (owner rule R24, the frontend half, 2026-09-17). The backend declares every event field ONCE
in afc_tournament_and_scrims/event_contract.py and generates its six readers and writers from it.
The four frontend forms (admin create / edit, organizer create / edit) still list the fields by
hand with `formData.append("<key>", ...)`, which is the twelve-copies problem the contract exists
to end. Rewriting those forms is a separate build; what this tool gives now is the ONE list on the
frontend side (`lib/eventContract.generated.json`, written from this output) and the means for
`scripts/check-event-forms.mjs` to fail when a form and the contract disagree: a key a form sends
that the contract does not know (a typo, a dead field) blocks; a writable field no form sends is
counted and ledgered, so the copies can only converge.

It reads the owning module (R47), never the source text: `EVENT_FIELDS` is imported and walked.

USAGE
    python tools/export_event_contract.py --json > ../wt-fe-ocr/lib/eventContract.generated.json
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "afc.settings")

# Keys edit_event and create_event write BY HAND, outside the contract (views.py, "Still handled by
# hand BELOW"): uploads, the sponsor pair that rewrites rows, event_type, the tier the classifier
# owns, and the collections that describe other objects. A form is right to send them.
HAND_WRITTEN = [
    "event_banner", "uploaded_rules", "images", "file",
    "is_sponsored", "sponsor_usernames",
    "event_type",
    "tournament_tier", "tier_overridden",
    "stages", "prize_distribution",
    "event_id",
]


def export():
    import django
    django.setup()
    from afc_tournament_and_scrims import event_contract as ec

    fields = []
    for f in ec.EVENT_FIELDS:
        fields.append({
            "name": f.name,
            "source": getattr(f, "source", None) or f.name,
            "read": f.read,
            "write": f.write,
            "computed": bool(getattr(f, "get", None)),
        })
    writable = {
        "organizer": sorted(f["name"] for f in fields if f["write"] in (ec.ORGANIZER, ec.PLAYER, ec.PUBLIC)),
        "admin": sorted(f["name"] for f in fields if f["write"] in (ec.ADMIN, ec.ORGANIZER, ec.PLAYER, ec.PUBLIC)),
    }
    return {
        "_about": "Generated by AFC-B tools/export_event_contract.py from event_contract.EVENT_FIELDS. Do not edit; regenerate (the frontend's check-event-forms fails when it is stale).",
        "fields": fields,
        "writable": writable,
        "hand_written": HAND_WRITTEN,
    }


if __name__ == "__main__":
    data = export()
    if "--json" in sys.argv:
        print(json.dumps(data, indent=2))
    else:
        print(f"{len(data['fields'])} fields, organizer may write {len(data['writable']['organizer'])}, admin {len(data['writable']['admin'])}, {len(data['hand_written'])} hand-written keys")
