from django.urls import path, include
from .views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # path("admin/", admin.site.urls),
    path('add-product/', add_product, name='add_product'),
    path('view-all-products/', view_all_products, name='view_all_products'),
    path('edit-product/', edit_product, name='edit_product'),
    path('delete-product/', delete_product, name='delete_product'),
    path('deactivate-product/', deactivate_product, name='deactivate_product'),
    path('view-current-stock-status/', view_current_stock_status, name='view_current_stock_status'),
    path('view-all-orders/', view_all_orders, name='view_all_orders'),
    path('orders-today/', orders_today, name='orders_today'),
    path('orders-this-week/', orders_this_week, name='orders_this_week'),
    path('orders-this-month/', orders_this_month, name='orders_this_month'),
    path('view-all-coupons/', view_all_coupons, name='view_all_coupons'),
    path('create-coupon/', create_coupon, name='create_coupon'),
    path('activate-product/', activate_product, name='activate_product'),
    path('view-product-details/', view_product_details, name='view_product_details'),
    path("add-product-variant/", add_product_variant, name="add_product_variant"),
    path("delete-product-variant/", delete_product_variant, name="delete_product_variant"),
    path("add-to-cart/", add_to_cart, name="add_to_cart"),
    path("get-my-cart/", get_my_cart, name="get_my_cart"),
    path("remove-from-cart/", remove_from_cart, name="remove_from_cart"),
    path("update-cart-item-quantity/", update_cart_item_quantity, name="update_cart_item_quantity"),
    path("clear-cart/", clear_cart, name="clear_cart"),
    path("buy-now/", buy_now, name="buy_now"),
    path("verify-paystack-payment/", verify_paystack_payment, name="verify_paystack_payment"),
    path("paystack-webhook/", paystack_webhook, name="paystack_webhook"),
    path("get-my-orders/", get_my_orders, name="get_my_orders"),
    path("get-order-details/", get_order_details, name="get_order_details"),
    path("get-order-details-for-admin/", get_order_details_for_admin, name="get_order_details_for_admin"),
    path("mark-order-as-paid/", mark_order_as_paid, name="mark_order_as_paid"),
    path("delete-coupon/", delete_coupon, name="delete_coupon"),
    path("edit-coupon/", edit_coupon, name="edit_coupon"),
    path("get-weekly-usage-and-saving-generated/", get_weekly_usage_and_saving_generated, name="get_weekly_usage_and_saving_generated"),
    path("deactivate-coupon/", deactivate_coupon, name="deactivate_coupon"),
    path("activate-coupon/", activate_coupon, name="activate_coupon"),
    path("get-total-customer-savings/", get_total_customer_savings, name="get_total_customer_savings"),
    path("get-total-coupon-uses/", get_total_coupon_uses, name="get_total_coupon_uses"),
    path("get-total-revenue-generated/", get_total_revenue_generated, name="get_total_revenue_generated"),
    path("get-coupon-conversion-rate/", get_coupon_conversion_rate, name="get_coupon_conversion_rate"),
    path("get-coupon-details/", get_coupon_details, name="get_coupon_details"),
    path('get-coupon-details-with-code/', get_coupon_details_with_code, name='get_coupon_details_with_code'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)